### ISSUE TITLE
ToricVarieties: A few minor changes/additions

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1036]
A few changes/additions:
- Addition and scalar multiplication of toric divisors, elements of the class group and pic group.
- char, divT, cdivT, cl and pic in names of maps

**Comment by fingolfin** [comment]
What does "char, divT, cdivT, cl and pic in names of maps" mean?

**Comment by HereAround** [comment]
The terminology is from the toric geometry book by Cox-Little-Schenk for a toric variety X:

- Div_T(X) = group of torus invariant Weil divisors on X
- CDiv_T(X) = group of torus in variant Cartier divisors on X
- Cl(X) = class group of X
- Pic(X) = Picard group of X

In making contact with this notation, one could be tempted (and so at least I was until now) to replace "map_from_cartier_divisor_group_to_picard_group" by "map_from_cdivT_to_pic".

Beyond consistency, I found the usage of the mappings among these spaces cumbersome. Example:
1. `map_from_character_to_principal_divisors` 
2. `map_from_weil_divisors_to_class_group`

The codomain of 1 is identical to the domain of 2, namely Div_T. Yet, the names are (for yet other reasons - the image of 1 are the principal divisors) distinct. When I originally added this code, I believe this to be a good idea. But after using it for a while, at least I could not get my head around this. And this seems to be reflected in the feedback that @lkastner and I received from @simontelen, who has been using the toric geometry over the last couple of months for his lecture.

Here is another instance of this sort:

3. `map_from_cartier_divisor_group_to_torus_invariant_divisor_group`

Similar phenomenon: The codomain of this map is identical to Div_T, but carries yet a different name.

Since people do not seem to be in favor of `divT` and alike, maybe we could at least try to not have different names for identical groups/(co)domains. How about this:

Current names:
- `torusinvariant_divisor_group` (= Div_T),
- `cartier_divisor_group` (=CDiv_T),
- `class_group` (=Cl),
- `picard_group` (=Pic),
- `map_from_character_to_principal_divisors`,
- `map_from_weil_divisors_to_class_group`,
- `map_from_cartier_divisor_group_to_torus_invariant_divisor_group`,
- `map_from_cartier_divisor_group_to_picard_group`

New names:
- `torus_invariant_weil_divisor_group`,
- `torus_invariant_cartier_divisor_group`,
- `class_group`,
- `picard_group`,
- `map_from_character_lattice_to_torus_invariant_weil_divisor_group`,
- `map_from_torus_invariant_weil_divisor_group_to_class_group`,
- `map_from_torus_invariant_cartier_divisor_group_to_torus_invariant_weil_divisor_group`,
- `map_from_torus_invariant_cartier_divisor_group_to_picard_group`.

The individual names for the first four items are debatable, but the key being that they appear in exactly this wording in the following four function names. Is this something that people (@lkastner @thofma) could relate to?

If not, then I follow what @lkastner already said and will drop this from https://github.com/oscar-system/Oscar.jl/pull/1056/commits/e9ced7c5eeb4b2850fed9877e10959747698815f to simplify matters.

**Comment by fingolfin** [comment]
I agree that it is quite confusing that the "same" (co)domain is referred to by different names in different context. 

Taking a step back, I notice: What you have here is a bunch of groups, and then certain canonical (?) maps between them. 

If I may dream for a moment, (and ignoring technical issues for the moment), what if we replaced e.g. `map_from_character_to_principal_divisors(v)` by something akin to this:
```
  canonical_map(character_lattice(v), divisor_group(v))
```

Of course this may be "obviously silly" to you, as I have no idea about the math/definitions.

Regarding that, some mathematical questions:
- since you insist on prefixing with "torus_invariant", does that mean `Div_T` is a subgroup of some "full" divisor group `Div` ?
  - if so, how likely is it that you'll ever need this "full" divisor group?
- is `CDiv_T` a natural/canonical subgroup of `Div_T`? I.e., is `map_from_cartier_divisor_group_to_torus_invariant_divisor_group` an embedding?

**Comment by thofma** [comment]
In case what @fingolfin is not possible, I would suggest we keep the "new names" you listed above for the moment.

**Comment by lkastner** [comment]
> I agree that it is quite confusing that the "same" (co)domain is referred to by different names in different context.
> 
> Taking a step back, I notice: What you have here is a bunch of groups, and then certain canonical (?) maps between them.
> 
> If I may dream for a moment, (and ignoring technical issues for the moment), what if we replaced e.g. `map_from_character_to_principal_divisors(v)` by something akin to this:
> 
> ```
>   canonical_map(character_lattice(v), divisor_group(v))
> ```
I am afraid that this cannot be determined from the arguments alone, but I will think about this. It seems like `canonical_map` is not taken yet, so there is no danger of interfering with other stuff?
> 
> Of course this may be "obviously silly" to you, as I have no idea about the math/definitions.
> 
> Regarding that, some mathematical questions:
> 
>     * since you insist on prefixing with "torus_invariant", does that mean `Div_T` is a subgroup of some "full" divisor group `Div` ?
Yes, it is the subgroup of torus invariant objects there.
>       
>       * if so, how likely is it that you'll ever need this "full" divisor group?
Unlikely, since most of the time one works modulo equivalence and the good thing is that there is a torus invariant representative in any class.
> 
>     * is `CDiv_T` a natural/canonical subgroup of `Div_T`? I.e., is `map_from_cartier_divisor_group_to_torus_invariant_divisor_group` an embedding?
Yes. (@HereAround will correct me, I haven't "worked" with toric geometry since I started at TU)

**Comment by HereAround** [comment]
I agree with @lkastner. From what I hear, we can all agree to the following long names (as proposed above):

- `torus_invariant_weil_divisor_group`,
- `torus_invariant_cartier_divisor_group`,
- `class_group`,
- `picard_group`,
- `map_from_character_lattice_to_torus_invariant_weil_divisor_group`,
- `map_from_torus_invariant_weil_divisor_group_to_class_group`,
- `map_from_torus_invariant_cartier_divisor_group_to_torus_invariant_weil_divisor_group`,
- `map_from_torus_invariant_cartier_divisor_group_to_picard_group`.

So I will rebase https://github.com/oscar-system/Oscar.jl/pull/1056 accordingly.
