### ISSUE TITLE
Inconsistent behaviour of kernel

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#1062]
As already discussed in Slack, there is some inconsistency with what `kernel` returns (and in particular with `kernel` and `nullspace`).
Sometimes the output just contains the basis, sometimes there are additional zero columns.
```
julia> M = matrix(GF(2), [ 1 0 1; 1 0 1]);

julia> kernel(M)[2] # calling Hecke
[0   1   0]
[1   0   0]
[0   1   0]

julia> nullspace(M)[2] # calling AbstractAlgebra
[0   1]
[1   0]
[0   1]
```
Also, the echelon structure is sometimes different:
```
julia> M = matrix(ZZ, [ 1 0 1; 1 0 1]);

julia> kernel(M)[2] # calling Hecke
[ 1   0]
[ 0   1]
[-1   0]

julia> nullspace(M)[2] # calling AbstractAlgebra
[0    1]
[1    0]
[0   -1]
```
Regarding the second point: I have the impression that the basis of the kernel is always in a reduced column echelon form, but this is not documented, so one cannot rely on it. Would it be possible to guarantee something here, like that the basis is always in lower-left reduced column echelon form?

**Comment by lkastner** [comment]
It seems the issue is actually with `right_kernel`. When `AbstractAlgebra.jl` calls `kernel` internally it calls `right_kernel`, since that is the default. The `right_kernel` from AA does the right thing, could it be overwritten by the `Hecke` one?

**Comment by fieker** [comment]
OK: the 1st cannot be changed, the reason is that kernel in this case is actually calling flint (alike "all" specialised linear algebra and in flint all such functions are inplace. The dataformat of flint matrices could/ can allow to remove rows, but it cannot change the number of columns, hence ther return value has the full matrix and the rank.
For generic matrices (AA and many ring types) this is done in Julia and thus gives different results.
As to the echelon form: my expectation is that this will in general not be true - and potentially expensive to add.

**Comment by lkastner** [comment]
The documentation at
https://docs.oscar-system.org/dev/AbstractAlgebra/matrix/#kernel-Union{Tuple{MatElem{T}},%20Tuple{T}}%20where%20T%3C:RingElem
says that kernel contains a basis. This is the documentation coming from AA, so it is a bug if we do not return a basis.

I managed to narrow down the bug:
```
julia> k=Oscar.GF(2)
Galois field with characteristic 2

julia> MS = MatrixSpace(k,3,2)
Matrix Space of 3 rows and 2 columns over Galois field with characteristic 2

julia> Mac = zero(MS)
[0   0]
[0   0]
[0   0]

julia> Mac[1,1] = Mac[1,2] = 1
1

julia> kernel(Mac)
(1, [1 0 0; 1 0 0])

julia> k=AbstractAlgebra.GF(2)
Finite field F_2

julia> MS = MatrixSpace(k,3,2)
Matrix Space of 3 rows and 2 columns over Finite field F_2

julia> Mac = zero(MS)
[0   0]
[0   0]
[0   0]

julia> Mac[1,1] = Mac[1,2] = 1
1

julia> kernel(Mac)
(1, [1; 1])
```
If the documentation is for `kernel` is from AA, maybe we should use this? I don't understand completely yet what `@code_typed` does, but it seems like
```
julia> @code_typed kernel(Mac)
CodeInfo(
1 ─ %1 = invoke AbstractAlgebra.:(var"#kernel#147")(:right::Symbol, #self#::typeof(kernel), A::fpMatrix)::Tuple{Int64, fpMatrix}
└──      return %1
) => Tuple{Int64, fpMatrix}
```
indicates that we are actually going down the right route at first. However following the code I see
```
julia> @code_typed left_kernel(transpose(Mac))
CodeInfo(
1 ─ %1 = invoke Hecke.transpose(x::fpMatrix)::fpMatrix
│   %2 = invoke Hecke.right_kernel(%1::fpMatrix)::Tuple{Int64, fpMatrix}
│   %3 = Base.getfield(%2, 1)::Int64
│   %4 = Base.getfield(%2, 2)::fpMatrix
│   %5 = invoke Hecke.transpose(%4::fpMatrix)::fpMatrix
│   %6 = Core.tuple(%3, %5)::Tuple{Int64, fpMatrix}
└──      return %6
) => Tuple{Int64, fpMatrix}

julia> @code_typed AbstractAlgebra.left_kernel(transpose(Mac))
CodeInfo(
1 ─ %1 = invoke Hecke.transpose(x::fpMatrix)::fpMatrix
│   %2 = invoke Hecke.right_kernel(%1::fpMatrix)::Tuple{Int64, fpMatrix}
│   %3 = Base.getfield(%2, 1)::Int64
│   %4 = Base.getfield(%2, 2)::fpMatrix
│   %5 = invoke Hecke.transpose(%4::fpMatrix)::fpMatrix
│   %6 = Core.tuple(%3, %5)::Tuple{Int64, fpMatrix}
└──      return %6
) => Tuple{Int64, fpMatrix}
```
This confuses me a bit. Maybe it has to go down this route, since it used `Hecke.GF`? Is it some invalidation/specialization issue? Anyway, the documentation should fit the behavior.

**Comment by fieker** [comment]
On Thu, Mar 16, 2023 at 04:45:27AM -0700, Lars Kastner wrote:
> The documentation at
> https://docs.oscar-system.org/dev/AbstractAlgebra/matrix/#kernel-Union{Tuple{MatElem{T}},%20Tuple{T}}%20where%20T%3C:RingElem
> says that kernel contains a basis. This is the documentation coming from AA, so it is a bug if we do not return a basis.
> 
The documentation is wrong.
for left_kernel one seems to get a basis as rows can be removed
for right_kernel one gets a generating system, but the matrix can have
zero cols.


Oscar and AA differ as AA.GF(2) has absolutely nothing in common with
Nemo.GF(2). In particular, AA.GF(2) and matrices aver it are pure julia,
while matrices over Nemo.GF(2) are in C and potentially optimized.

**Comment by fieker** [comment]
The AA.GF stuff should be removed from the surface of the planet -
jointly with AA.NumberField and similar

They were added mainly to have at least some rings in AA in order to
test the generic algorithms.

**Comment by lkastner** [comment]
So if they are needed for testing, then maybe we could change to not export them from AA and prefix them with `_`? Then they could still be used in the tests.

Nevertheless, the docs for AA are actually right for the implementation from there. Of course we could just change it to not say "basis" anymore, but that seems unfair to the algorithm from AA...

**Comment by lgoettgens** [comment]
The inconsistency issue is present in pure AA as well. Consider the following mwe:
```julia
julia> m = matrix(QQ, 2, 2, [1,0,0,0])
[1   0]
[0   0]

julia> kernel(m)
(1, [0; 1])
```
Even though the matrix is of type `Nemo.QQMatrix`, this will only call AA methods (as one can trace e.g. with `@which`). At some point doing this, the docstring changes from stating that it will return a basis to a generating system (first seen at `nullspace`).

**Comment by joschmitt** [comment]
I'm not sure I see the point. Where is the inconsistency in the example?

**Comment by lgoettgens** [comment]
> I'm not sure I see the point. Where is the inconsistency in the example?

Nothing, just me being stupid. Sorry :sweat_smile:
