### ISSUE TITLE
Glitch in manual: unexpected extra method for `base_ring` appears

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1143]
Reported by @wdecker : in the section [Data Associated to Ideals](https://oscar-system.github.io/Oscar.jl/dev/CommutativeAlgebra/ideals/#Data-Associated-to-Ideals) of the manual, the documentation for `base_ring(I::MPolyIdeal)` unexpected also shows the docstring for `base_ring(M::PMat)` from Hecke.jl:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/241512/156738849-00a9f83c-2bbf-4f01-9d03-e4a32223e3aa.png">

The corresponding section in `ideals.md` looks like this:
````md
## Data Associated to Ideals

```@docs
base_ring(I::MPolyIdeal)
```
````

**Comment by thofma** [comment]
Same as https://github.com/oscar-system/Oscar.jl/pull/548?

**Comment by fingolfin** [comment]
Oh, quite possibly. But this one here is concrete, and an issue, while that one introduces the issue as a PR, which is ... odd...

So, I'd rather close that PR, and leave this issue open. As @thofma pointed out there, this is likely https://github.com/JuliaDocs/Documenter.jl/issues/839 and/or https://github.com/JuliaDocs/Documenter.jl/issues/1523

**Comment by thofma** [comment]
I think the underlying issue is https://github.com/JuliaLang/julia/issues/29437. In the past I had (someimes) success with moving the `where` around.

**Comment by ThomasBreuer** [comment]
@fingolfin just for curiosity:
I had thought that reporting a problem via a pull request, as in #548, has the advantage that one can reproduce the situation.
When I open an issue, the problematic phenomenon may disappear because of (a side-effect of) some commit, perhaps without actually solving the problem.
So what is the recommended way to proceed, perhaps open both an issue and a pull request?

**Comment by fingolfin** [comment]
We don't show `base_ring` anymore in the relevant section, so this is resolved in that sense at least
