### ISSUE TITLE
Inconsistent use of is and is_ in function names

### ISSUE THREAD

**Issue by ulthiel** [oscar-system/Oscar.jl#1265]
Most of the functions testing for some property are named ```isproperty```. There are a few functions though which are named ```is_property```:
```
is_basepoint_free      is_isomorphism          is_projective_space     is_z_graded
is_closed_embedding    is_non_zero_divisor     is_q_cartier            is_zm_graded
is_dense               is_open_embedding       is_q_gorenstein
is_equal_with_morphism is_positively_graded    is_very_ample
```

This seems inconsistent to me.

(I personally would prefer ```is_property``` for better readability but it seems many things in Julia Base are already named ```isproperty```, so one should stick to this)

**Comment by thofma** [comment]
We decided to use `is_*` instead of `is*` (see the [Oscar style guide](https://oscar-system.github.io/Oscar.jl/dev/DeveloperDocumentation/styleguide/#Naming-conventions)) and we are gradually adjusting the various projects. New code is already using the new convention.

**Comment by ulthiel** [comment]
Wise decision, thanks! I haven't seen this part in the documentation, just deduced from the amount of functions that you seem to go for is*.

**Comment by fingolfin** [comment]
Of course we can't do this for existing Julia functions, such as `iseven`, `isfinite`, `iszero`, ... And probably shouldn't because people who are already familiar with Julia will expect them to work.

Yet this creates an annoying inconsistency *sigh*. I think we need to point this out somewhere in the docs.

Perhaps we should also set up aliases for some of these. Experimentally, the following seems to work reasonably well:
```julia
"""
    is_zero(x)

Alias for `iszero(x)`, provided for consistency with Oscar naming conventions.
"""
const is_zero = iszero
export is_zero
```

**Comment by thofma** [comment]
Yes, if I remember correctly the consensus was that if there is a corresponding julia function, we will have both.

**Comment by HereAround** [comment]
Why not use deprecate? I was under the impression that then the old functions still work. The user might even be informed by this about the change of name? I prepared the draft for the renaming in the toric varieties (mentioned above) accordingly.

**Comment by fingolfin** [comment]
`@deprecate` is not appropriate for aliasing `Base.iszero` and friends. First off, we are not (and can not and must not) deprecating `Base.iszero`! Secondly, it actually creates a *second* function object, and that can lead to issues unless every package renames everything at the same time. Otherwise, you'll end up with methods that are only available under one name, not both.

For our own functions, we could use it, but unless the user explicitly turns on deprecation warnings, there won't be any. Plus again those problems I mentioned above where code that by accident still provides a method under the  "old" name silently works but the method is not available under the "new" name.

I actually think a better migration strategy for us would be to rename things, but then add the old name via the `const oldname = newname` trick, and also still export it. We can then change "everything" in `AbstractAlgebra` and make a new, non-breaking release; then change it all in Nemo, Hecke, Singular, Polymake, GAP, and finally Oscar. Once all are changed we can then replace those `const oldname = newname` with `@deprecate`, or outright remove them in breaking releases.

Alternatively, we do a flag day during the coding sprint in 10 days, and do it all in one go during one day -- but that'll still risk breaking in-flight PRs, so I think I somewhat prefer the method sketched above.

That said, as always: if anybody (e.g. @thofma @benlorenz) spots issues with this idea or has a better idea, please speak up!

**Comment by ulthiel** [comment]
What are you doing about ```hasfunction```? Is it going to be ```has_function``` as well?

(Somehow, even though I find the ```is_``` stuff better, it'll be weird to deviate from Julia base...)

(Edit: Wow, you have stuff like ```hasisabelian```. That'll be interesting!)

**Comment by fingolfin** [comment]
Yes, also for `set_`. In fact this already started

**Comment by thofma** [comment]
I am happy with the `const ...` deprecation approach.

**Comment by lkastner** [comment]
See also https://github.com/oscar-system/Oscar.jl/issues/877

**Comment by fingolfin** [comment]
Since I was asked how this migration could work in practice, I see two models:

1. We change our packages one by one: first AbstractAlgebra, then Nemo, then Singular & Polymake & GAP, then Oscar. In each of them, we identify all functions to be renamed; we rename them, but also keep aliases for the old names via the `const OLDNAME = NEWNAME` trick described above. Once a package is updated and released, we can proceed to the next. Once all is done, and some time has passed (so that e.g. outstanding PRs have been merged etc.) we can repeat this once more to remove the aliases.

2. We do it "all at once", by adding *conditional* aliases: E.g. add stuff like this into `src/Oscar.jl` after including `imports.jl`:
```julia
if !isdefined(Oscar, :isfinite)
   """
       isfinite(x)

   Alias for `is_finite(x)`.
   """
   const isfinite = is_finite
elseif !isdefined(Oscar, :is_finite)
   """
       is_finite(x)

   Alias for `isfinite(x)`.
   """
   const is_finite = isfinite
end
```
Then I can immediately start using both variants (and e.g. rewrite everything to use `is_finite`. The same fragment can be used in all our packages. 

The advantage of this second approach is that it allows us to immediately replace some names in one package without having to coordinate with all packages at once.


Some more thoughts
- we could have macros to generate these "aliases" more conveniently, with all the checks and docstrings
- we need to decide: do we also want to provide `is_...` aliases for existing Julia functions like `isone`, `isfinite`, etc?
- should we eventually remove our "old" names, and only keep the new ones? What are the benefits and drawbacks to keeping both `is_normal` and `isnormal` around?

**Comment by thofma** [comment]
> 1. We [...]
> 2. We [...]

I personally would prefer 1.

> * we could have macros to generate these "aliases" more conveniently, with all the checks and docstrings

Hm, sounds good.

> * we need to decide: do we also want to provide `is_...` aliases for existing Julia functions like `isone`, `isfinite`, etc?

I would say yes.

> * should we eventually remove our "old" names, and only keep the new ones? What are the benefits and drawbacks to keeping both `is_normal` and `isnormal` around?

I would be in favor of removing the old names since I prefer there being one 'canonical' name. If I see
```
  is_normal(X) && isprojective(X)
```
I want to point out that this should be changed. But if we allow both, this is valid and I cannot complain about it :)

**Comment by fingolfin** [comment]
I've added an `@alias` macro in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1145

**Comment by fingolfin** [comment]
To all interested in the renaming, check out https://github.com/Nemocas/AbstractAlgebra.jl/pull/1145

**Comment by fingolfin** [comment]
I think this is resolved now, at least in general (if there are specific problems remaining, please point them out explicitly)
