### ISSUE TITLE
Collect deprecations in one place and document the process

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1567]
I added `Deprecations.jl`, but did not want to move all of them in the otherwise unrelated PR. So here is just a reminder to add the following:
- [ ] Would be good to have them in one place (also recording during which release cycle the deprecations took place). 
- [ ] This should get an entry in the developer documentation.

**Comment by fingolfin** [comment]
Somewhat related: In some cases, when we rename things, we first use `@alias` in the affected packages, so that we can gradually migrate to a new name, and have both names active and identical for a time. In a few cases we may wish to keep the alias indefinitely. But in many cases I expect we want to get rid of the old name eventually.

The process for this could be that once all packages have adapted the new name and had a release, we could replace `@alias` with corresponding `@deprecate` invocations, to give users a chance to find out about the renaming. And these then should of course be collected centrally (though in this "renaming in multiple packages" case we probably would track them  in other packages, not Oscar.jl?)

**Comment by lkastner** [comment]
I wasn't aware of this ticket. I'll collect the existing deprecations and mark them with the current release, I think doing git archaeology to figure out the exact release for every deprecation might be overkill.

I'll also add the developer docs entries.

**Comment by fingolfin** [comment]
I agree on the overkill

**Comment by thofma** [comment]
Agreed. We should not try to do it for the old deprecations, but only for newly added ones.
