### ISSUE TITLE
Group: issubgroup convention

### ISSUE THREAD

**Issue by shikil** [oscar-system/Oscar.jl#163]
Is it better that `issubgroup(H, G)` follow `issubset(a, b)` convention a ⊆ b?
https://github.com/oscar-system/Oscar.jl/blob/57984b34e34c5b6b9c919e113befd51b7ab2a10e/src/Groups/sub.jl#L67

**Comment by fieker** [comment]
On Fri, Sep 25, 2020 at 02:14:00AM -0700, shikil wrote:
> Is it better that `issubgroup(H, G)` follow `issubset(a, b)` convention a ⊆ b?
> https://github.com/oscar-system/Oscar.jl/blob/57984b34e34c5b6b9c919e113befd51b7ab2a10e/src/Groups/sub.jl#L67

Yep - and the same is "wrong" for submodules...

**Comment by fingolfin** [comment]
That's a very important point, thanks for brining it up. The origin of this clash is that we are combining different systems here with different conventions; groups are implemented via GAP, which has the convention (simplified in a nutshell) that function arguments are ordered in "decreasing size"; so the parent group comes first, subgroups next, then elements, etc.

This clashes with the Julia convention. I am inclined to say we should change to match `issubset`. At the same time, the GAP convention often is quite powerful for guessing function argument orders, so I'd like to ponder if we can replace it with a new similarly simple rule... we'll have to see.

And yeah, of course submodules etc. etc. should also have the same convention, and we should document the convention somewhere for future generations. As time passes, these things get harder and harder to change, as more and more code gets written relying on the behavior...

**Comment by thofma** [comment]
The julia convention is that infix operators `op` translate `a op b` to `op(a, b)`. This applies here, since
```julia
julia> [1, 2] ⊆ [1,2, 3]
true

julia> ⊆
issubset (generic function with 8 methods)
```
This rule seems pretty simple to me.

**Comment by fingolfin** [comment]
Yes, GAP has the same rule, e.g. for \in and \< (`isless`), which leads to some somewhat awkward exceptions to the general rule, but overall it's still OK. 

So, sure, this case is covered. It's all the remaining cases that I worry about. In GAP this is no big problem, as GAP has no corresponding operator for issubset and issubgroup, and hence can easily fall back to its general rule of "sort from largest to smallest argument".  

So naively I could use the rule "if there is a corresponding binary op, then make sure the order matches; otherwise, order arguments from largest to smallest". Problem is that there is no operator corresponding to `issubgroup` in Oscar or Julia right now (although I guess we could abuse `<=` for it, if we are careful to also overload `<`, `>=`, `>`, as this is just a partial order). So by that rule, `issubgroup` would behave as it does right now, and thus opposite to `issubset`.

Ah well, for now I guess we'll have to resort to "use whatever order you think is useful, e.g. because it matches what your system of origin uses it (here: GAP), except when you have a good reason to do differently." I can do that, but I wonder how many more gotchas we'll hit this way. Also, when updating `issubgroup`, we'll have to add a big warning comment for GAP users about the different order (which is fine -- I prefer it over the the alternative of adding a big warning for Julia users. And apparently Magma and Julia match here, too, so that's another argument *for* the change).

**Comment by fingolfin** [comment]
We ultimately resolved this by removing `issubgroup` -- just use `issubset` (with the "usual" argument order)

**Comment by fingolfin** [comment]
Not sure why I closed this, as `is_subgroup` still is there... and differs from `issubset` in that it also returns an embedding...
