### ISSUE TITLE
Basic geometry code still needed?

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1651]
`src/geometry/basics.jl` contains basic definitions for (weighted) projective spaces. We have this and more with toric geometry (once https://github.com/oscar-system/Oscar.jl/pull/1646 is merged). @fieker (unless I am mistaken you worked most on this file) I wonder if this code is then still needed? If yes, we should document it.

**Comment by fingolfin** [comment]
The code in question now lives in `src/AlgebraicGeometry/Miscellaneous/basics.jl` and indeed was written by @fieker, IIRC in order to support the code in `experimental/PlaneCurve/`.

I think it has a different range of supported cases (e.g. it can be used over Z/nZ).

We discussed this before: there are many different "models" of projective spaces (as varieties, manifolds, incidence geometries, combinatorial objects, etc.), so it is unlikely we'll ever get away with a single universal one.

The  main question then is how to make the different implementations available. A function like `projective_space` should probably allow to select the implementation, but also have a default...


As it is, I don't think there is need to remove this code, and also we would loose some functionality...

**Comment by fingolfin** [comment]
See also the past discussion in issue #922

**Comment by joschmitt** [comment]
The file was removed in #3179.
