### ISSUE TITLE
Extend documentation for schemes

### ISSUE THREAD

**Issue by HereAround** [oscar-system/Oscar.jl#1689]
The code migrated from experimental to the main coding source in the following PRs needs to be documented:
- https://github.com/oscar-system/Oscar.jl/pull/1680
- https://github.com/oscar-system/Oscar.jl/pull/1681
- https://github.com/oscar-system/Oscar.jl/pull/1682

**Comment by HechtiDerLachs** [comment]
Thanks for raising this issue. As already mentioned in oral communications earlier, I suggest to start off with the documentation of the `CoveredScheme`, since this is the user-facing part. The average user will most likely never see a `Glueing` or a `SimpleGlueing` working in the background. Thus, we need a user-facing documentation for the first, but up to now merely docstrings for the latter. 

If you start working on a particular file, it would be good to leave us a note in this thread so that we do not accidentally do double work.
