### ISSUE TITLE
Memory leak while accessing polymake incidence matrix

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#1742]
MWE: 
```
using Oscar
M = matroid_from_matrix_columns(matrix(QQ,[[1,2,3],[9,8,7]]);check=false)
B = Polymake.tropical.matroid_fan{min}(M.pm_matroid)

while true
    _ = B.MAXIMAL_POLYTOPES[1,:]
end
```

Accessing `MAXIMAL_POLYTOPES` allocates more and more RAM until it eventually crashes julia.

**Comment by benlorenz** [comment]
This is not really a memory leak, if you call the garbage collection manually the memory usage is completely stable:

```julia
julia> GC.enable_logging(true)
julia> i = 0;
julia> while true
           _ = B.MAXIMAL_POLYTOPES[1,:]
           if i%1000000 == 0
              GC.gc(false)
           end
           i+=1
       end
GC: pause 25.07ms. collected 123.568698MB. incr 
GC: pause 166.42ms. collected 84.864928MB. incr 
GC: pause 169.91ms. collected 293.159456MB. incr 
GC: pause 111.20ms. collected 204.501760MB. incr 
GC: pause 163.66ms. collected 110.322400MB. incr 
GC: pause 181.87ms. collected 303.991808MB. incr 
GC: pause 178.96ms. collected 303.991808MB. incr 
GC: pause 181.29ms. collected 303.991808MB. incr 
GC: pause 184.29ms. collected 303.991808MB. incr 
...
```

I tried inserting some `GC.safepoint()` calls into a few key functions that get called all the time but that does not help without the explicit `gc` call. I think the reason is not a missing opportunity for the garbage collection to happen but julia doesn't seem to believe it is necessary because it is not aware of all the memory behind various pointers.
Forcing it to run manually will collect all CxxWrap-based pointers which then cleans up all corresponding polymake-C++-objects and the memory usage is kept down.

We might be able to improve that if we can get more polymake allocations routed through the julia memory management, currently only GMP allocations will use the `jl_` functions. But this might be tricky.


If you write enough julia code within that loop which regularly triggers a garbage collection the problem should not happen.

**Comment by YueRen** [comment]
I see, I guess I need to be more careful whilst using internal objects and functions.

**Comment by micjoswig** [comment]
@YueRen maybe you want to close this issue?
