### ISSUE TITLE
Argument order in `is_maximal`, `is_normal`, `is_characteristic`, ...

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#1793]
All these commands take two groups as argument. This opens up a chance for mixing the orders up.

One order is to have the "parent" group first -- this is what we do now and is based on the order GAP has it in. It also means that the order `is_normal(G,N)` matches e.g. `quo(G,N)` and `index(G,N)`. But at the same time, `is_subset = issubset` which comes from Julia has the *other* order, as it follows the mathematical ordering: `is_subset(A,B)$ is defined as $A \subseteq B$. (See also the related discussion on  `is_subgroup`  at issue #163 ; also related: https://github.com/kalmarek/GroupsCore.jl/issues/17)

So, there is an argument for swapping the argument order... Alas, no matter what we use, *someone* will be confused and mix it up. So one could also think about ways to help catch such mistakes:

For `is_maximal`, one could deal with this at least in some degree, by adding a subgroup check, and if the argument which is meant to be the subgroup isn't actually a subgroup, raise an error. Alternative or in addition, one could rename it to `is_maximal_in(A,B)` and define it as testing that "A is maximal in B".

For `is_normal` and `is_characteristic`, this is not really an option, as those are defined for arbitrary pairs of (sub)groups with a common parent. E.g. right now, `is_normal(A,B)` iff $A \leq N_G(B)$.  In the special case that $B\leq A$ holds, this is equivalent to testing that $B$ is a normal subgroup of $A$. 

One way around this might be to replace these functions with two news ones each:
- `is_normalized_by(A,B)` checks if `A` is normalized by `B`, so $A\leq N_G(B)$` (the reverse order to what we have now)
- `is_normal_subgroup(A,B) = issubset(A,B) && is_normalized_by(A,B)`

Unfortunately I am not sure what to call the analog to `is_normalized_by` for "characteristic"... I was thinking `is_characteristic_in(A,B)` but that to be sounds like it requires that `A` be a subgroup of `B`.

**Comment by thofma** [comment]
I confess that we have not been consistent for some of these functions in the number theoretic part too (see also the `divides` accident). Here are some thoughts:

1) We could go with "parent first" and make `issubset` an error for our objects, which should refer to `is_subset` and mention the "right order".
2) We don't go "parent first" and adjust to "julia's style", which follows more how we *talk* about these concepts. For example, it would be `index(H, G)` because one speaks of the index of $H$ in $G$ (`index(H, G)` would not stand for the expression $[G : H]$). Note that it would still be `quo(G, N)` because it is the quotient of $G$ by $H$. It has some merits. Once one gets used to the fact that `verb(x, y)` always means `x verb y` (or `preposition` instead of `verb`), one never has to wonder about the order for `in(x, y)` or `occursin(x, y)`.

I have no strong opinion, but we should try to be consistent as usual.

**Comment by ThomasBreuer** [comment]
- `is_maximal(H, G)` currently makes already a subgroup check, and returns `false` if `G` is not a `subgroup` of `H`. Thus we change the behaviour of `is_maximal` if we now throw an error in the situation that the subgroup relation does not hold. Still this change is harmless in the sense that users will perhaps get more error messages (but not wrong results) when we change the order of arguments and add a subset check.
(We can provide an optional `check` argument in order to omit the subgroup check.)
- Replacing `is_normal(G, H)` by `is_normalized_by(H, G)` and `is_normal_subgroup(H, G)` is fine.
  For the moment, the old `is_normal(G, H)` can remain available as a deprecated function.
- Concerning the variant of `is_characteristic` that checks invariance of `H` under the full automorphism group of `G` also if `H` is not a subgroup of `G`:
GAP's `IsCharacteristicSubgroup` may run into an error if the second argument is not a subset of the first argument.
Thus I think we can change the argument order and change the documentation such that a subgroup check is made except if one sets the keyword argument `check` to `false`. Shall we keep the name `is_characteristic` then?
(Of course also the GAP documentation should be improved.)
- `is_subgroup` comes from Hecke, thus we cannot just remove it, and we have to change the argument order for `GAPGroup`  arguments, and add a warning about the changed argument order. And we should recommend to better use `is_subset` instead of `is_subgroup`.

I am going to provide a pull request for the necessary changes.

**Comment by ThomasBreuer** [comment]
I just observed that also `embedding(G, H)` in `src/Groups/sub.jl` has the wrong argument order. Changing the argument order will not cause wrong results because the subset check must be made anyhow.
