### ISSUE TITLE
Choice of variable names interferes with variables in Singular libraries

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#1905]
The absolute primary decomposition is broken:
```
julia> R, (psi, ) = PolynomialRing(QQ, ["psi"])
(Multivariate Polynomial Ring in psi over Rational Field, fmpq_mpoly[psi])

julia> absolute_primary_decomposition(ideal([psi]))
   skipping text from `)` error at token `)`
ERROR: Could not call function
Stacktrace:
 [1] call_singular_library_procedure
   @ ~/.julia/packages/CxxWrap/IdOJa/src/CxxWrap.jl:618 [inlined]
 [2] low_level_caller_rng(lib::String, name::String, ring::Singular.PolyRing{Singular.n_Q}, args::Singular.sideal{Singular.spoly{Singular.n_Q}})
   @ Singular ~/.julia/dev/Singular/src/caller.jl:374
 [3] absPrimdecGTZ(ring::Singular.PolyRing{Singular.n_Q}, args::Singular.sideal{Singular.spoly{Singular.n_Q}})
   @ Singular.LibPrimdec ~/.julia/dev/Singular/src/Meta.jl:49
 [4] absolute_primary_decomposition(I::MPolyIdeal{fmpq_mpoly})
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly-ideals.jl:574
 [5] top-level scope
   @ REPL[7]:1
```

Here it is more clear from the error what is happening:
```
julia> R, (p, psi) = PolynomialRing(QQ, ["p", "psi"])
(Multivariate Polynomial Ring in p, psi over Rational Field, fmpq_mpoly[p, psi])

julia> absolute_primary_decomposition(ideal([2//27*p^3 + psi]))
`int` * `map` failed
expected `int` * `int`
expected `int` * `matrix`
expected `int` * `bigintmat`
expected `int` * `intvec`
expected `int` * `intmat`
...parse error
error occurred in or before primdec.lib::absPrimdecGTZ_i line 5872: `K=a,p^3+(27*psi)/2,a;`
```
We have a variable called `psi`, but this interferes with the `psi` in the Singular library function, which seems to be a map.

I know that we had naming problems before and I can of course add `"psi"` to the list here: https://github.com/oscar-system/Singular.jl/blob/master/src/MessyHacks.jl#L164. The problem I see is that this works now for this function. But I can imagine a situation where we are interfering with things in the Singular library and the result will silently be wrong (without error). Maybe there is a better way?  @hannes14? @fingolfin? Not sure who to ask.

Edit: Reported by @apturner

**Comment by fingolfin** [comment]
Yeah adding a list of specific names that are forbidden is not a long-term viable solution. After all Singular libraries could define variables with arbitrary names, right?

Perhaps we need to make all variable names unique on the Singular side, e.g. by changing `x` to `OSCAR_x` and so on.... Of course then we need to rename back and force as we move between the systems. So hopefully there is a better solution. I'll talk to @hannes14 about it.

**Comment by thofma** [comment]
Maybe it is only a problem because of the usage of `execute` in the respective function of primdec.lib. Not sure.

**Comment by fingolfin** [comment]
Yeah, I discussed this earlier with @hannes14 and it is precisely due to remaining uses of `execute`: a new ring is constructed whose variables should have the same names as that of the input ring; but during this construction, the name of the local variable `phi`...

@hannes14 said that "most" calls to `execute` were removed some time ago -- well, or at least that's how I understood him, I probably misunderstood, given that I just counted 460 in the Singular library :joy:

So as I understand it, the new plan is to adjust the Singular library code to prefix local variable with `@` to avoid these conflicts (and then we should make sure to forbid `@` in variable names on the Oscar side)

**Comment by thofma** [comment]
https://github.com/oscar-system/Singular.jl/blob/master/src/MessyHacks.jl#L185 prepends strings with `@` before passing to Singular. I think for an empty string `x = ""` we could end up with some variable whose name is prefixed with `@`?

**Comment by fingolfin** [comment]
Still broken in current Oscar, but fixed in Singular itself. We'll soon update Singular_JLL, Singular.jl etc., then this should be fixed.

**Comment by fingolfin** [comment]
This works now for the initial examples.

It still fails if one uses the variable name `@phi`. So maybe we should forbid that, and/or transform the variable name when going to Singular?

**Comment by fingolfin** [comment]
This variable name mapping would be useful to support other things as well?

We agreed that @mjrodgers will poke a bit at this.

**Comment by fingolfin** [comment]
Sitting here with @mjrodgers and looking into this.

The original error is gone, but of course we can still produce it if we change the variable to match the change in Singular:
```
julia> absolute_primary_decomposition(ideal([psi]))
   skipping text from `)` error at token `)`
ERROR: Could not call function
Stacktrace:
 [1] call_singular_library_procedure
   @ ~/.julia/packages/CxxWrap/aXNBY/src/CxxWrap.jl:624 [inlined]
 [2] low_level_caller_rng(lib::String, name::String, ring::Singular.PolyRing{Singular.n_Q}, args::Singular.sideal{Singular.spoly{Singular.n_Q}})
   @ Singular ~/.julia/packages/Singular/Q0BKF/src/caller.jl:373
 [3] absPrimdecGTZ(ring::Singular.PolyRing{Singular.n_Q}, args::Singular.sideal{Singular.spoly{Singular.n_Q}})
   @ Singular.LibPrimdec ~/.julia/packages/Singular/Q0BKF/src/Meta.jl:45
 [4] __compute_absolute_primary_decomposition__(I::MPolyIdeal{QQMPolyRingElem})
   @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly-ideals.jl:624
 [5] #245
   @ ~/.julia/packages/AbstractAlgebra/YkCOC/src/Attributes.jl:357 [inlined]
 [6] get!(default::Oscar.var"#245#247"{MPolyIdeal{QQMPolyRingElem}}, h::Dict{Symbol, Any}, key::Symbol)
   @ Base ./dict.jl:468
 [7] get_attribute!
   @ ~/.julia/packages/AbstractAlgebra/YkCOC/src/Attributes.jl:230 [inlined]
 [8] absolute_primary_decomposition(I::MPolyIdeal{QQMPolyRingElem})
   @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly-ideals.jl:618
 [9] top-level scope
   @ REPL[44]:1
```

Also, afterwards Singular.jl seem to be in bad state or so, because the next commands involving Singular may fail now, e.g.:
```
julia> R, (psi, ) = PolynomialRing(QQ, ["psi"])
(Multivariate polynomial ring in 1 variable over QQ, QQMPolyRingElem[psi])

julia> absolute_primary_decomposition(ideal([psi]))
ERROR: can not convert map(@psi) -> matrix
incompatible type in list assignment
...parse error
error occurred in or before primdec.lib::absPrimdecGTZ_i line 5878: `@K=a,@psi,a;`
last reserved name was `execute`
leaving primdec.lib::absPrimdecGTZ_i (0)
execute(`string`) failed
...parse error

Stacktrace:
  [1] error(s::CxxWrap.StdLib.StdStringAllocated)
    @ Base ./error.jl:35
  [2] check_error
    @ ~/.julia/packages/Singular/Q0BKF/src/libsingular/errors.jl:3 [inlined]
  [3] divexact(x::Singular.n_Q, y::Singular.n_Q; check::Bool)
    @ Singular ~/.julia/packages/Singular/Q0BKF/src/number/n_Q.jl:241
  [4] divexact
    @ ~/.julia/packages/Singular/Q0BKF/src/number/n_Q.jl:237 [inlined]
  [5] //
    @ ~/.julia/packages/AbstractAlgebra/YkCOC/src/Fields.jl:13 [inlined]
  [6] Rationals
    @ ~/.julia/packages/Singular/Q0BKF/src/number/n_Q.jl:403 [inlined]
  [7] (::Singular.Rationals)(a::QQFieldElem)
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly.jl:425
  [8] (::Singular.PolyRing{Singular.n_Q})(f::QQMPolyRingElem)
    @ Singular ~/.julia/packages/Singular/Q0BKF/src/poly/poly.jl:1535
  [9] singular_assure(I::Oscar.IdealGens{QQMPolyRingElem})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly.jl:635
 [10] singular_assure
    @ ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly.jl:622 [inlined]
 [11] __compute_absolute_primary_decomposition__(I::MPolyIdeal{QQMPolyRingElem})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly-ideals.jl:623
 [12] #245
    @ ~/.julia/packages/AbstractAlgebra/YkCOC/src/Attributes.jl:357 [inlined]
 [13] get!(default::Oscar.var"#245#247"{MPolyIdeal{QQMPolyRingElem}}, h::Dict{Symbol, Any}, key::Symbol)
    @ Base ./dict.jl:468
 [14] get_attribute!
    @ ~/.julia/packages/AbstractAlgebra/YkCOC/src/Attributes.jl:230 [inlined]
 [15] absolute_primary_decomposition(I::MPolyIdeal{QQMPolyRingElem})
    @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Rings/mpoly-ideals.jl:618
 [16] top-level scope
    @ REPL[52]:1
```

But if I repeat the failed command, it just works:
```
julia> absolute_primary_decomposition(ideal([psi]))
1-element Vector{Tuple{MPolyIdeal{QQMPolyRingElem}, MPolyIdeal{QQMPolyRingElem}, MPolyIdeal{AbstractAlgebra.Generic.MPoly{nf_elem}}, Int64}}:
 (ideal(psi), ideal(psi), ideal(psi), 1)
```

I think that's another bug in the Singular.jl error handling. I'll open an issue there.

**Comment by mjrodgers** [comment]
To sum up

* The variable name `"psi"` actually works fine (now), this was I think fixed by explicitly adding it to a list of "bad names" (though I can't find exactly where).
* The variable name `"phi"` does not work
* The variable names `"@psi"` and `"@phi"` also do not work.
All of these seem to be from (several different) `execute()` statements in the Singular `primdec.lib`, for example at [this line](https://github.com/Singular/Singular/blob/spielwiese/Singular/LIB/primdec.lib#LL3337C7-L3337C40):
```
execute("map phi=gnir,"+@va+";");
```
this gives an issue with a variable named `"phi"` because it clashes with the map name; the execute statements clashing with `"@phi"`/`"@psi"` occur in other places in the library. There are also execute statements with other variable names, that I couldn't explicitly trigger a bug with but potentially any variable name hardcoded into an `execute()` statement could lead to a clash of some sort...

In this case, the current Oscar method to fix a "bad name" is to prepend the variable name with an `@`, but for these cases, the `@<varname>` is ALSO used in the Singular library, so this just leads to another clash in a different part of the code.

(there is the separate issue of error handling where triggering this error will cause the next Singular call to also fail with the same error message)

**Comment by thofma** [comment]
I don't think anyone added `"psi"` to a list of bad names, see https://github.com/oscar-system/Singular.jl/blob/master/src/MessyHacks.jl#L159.

**Comment by mjrodgers** [comment]
Ah I see now, it was fixed on the Singular side. Also it seems this "messy hack" *appends* `@<number>`, and does not prepend the variable name, as I claimed in my previous comment.

**Comment by fieker** [comment]
On Thu, Jun 15, 2023 at 12:46:03PM +0000, Tommy Hofmann wrote:
> I don't think anyone added `"psi"` to a list of bad names, see https://github.com/oscar-system/Singular.jl/blob/master/src/MessyHacks.jl#L159.
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/oscar-system/Oscar.jl/issues/1905#issuecomment-1592977643
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


I think there are 2 different things going on here
 - makeing Oscar safe
 - makeing Singular safe

For Oscar we need
 - move to ascii only
 - possibly prepend by Oscar or similar

For Singular:
 - stop the use of any/ all vaiable names that have a meaning in some
   library
 - and/or rewrite the libraries to NOT depend on any name
 - for Singular.jl as well: move to ascii only

**Comment by mjrodgers** [comment]
Okay, the current rename function now does the following:
* if the variable name `x` is "bad" (at the moment this means it contains characters that aren't allowed, or `x == "minpoly"`) a transformation is applied to replace bad characters in a meaningful way, if this still results in a "bad" variable name then `x` is replaced with some default string (this is all left in place from the previous hack)
* since there is no way to catch all of the variable names that will give problems, we replace the string `x` with `"@OSCAR@"*x*"@"*string(i)` for an integer `i` that makes sure all of the variable names are unique.
This should completely avoid clashes with any variable names used in the Singular libraries. We only send ASCII variable names. In fact, we probably don't need to filter out `x == "minpoly"` anymore, but I supposed it doesn't hurt to leave it.

I was able to confirm that this bug also occurs in the standalone version of Singular, I will create a bug report there as well (though it looks difficult to fix in anything other than a superficial way).
