### ISSUE TITLE
Orders of matrix groups over arbitrary number field

### ISSUE THREAD

**Issue by joschmitt** [oscar-system/Oscar.jl#1930]
**Is your feature request related to a problem? Please describe.**
One cannot compute the order of a matrix group over a field that is not a cyclotomic field:
```
julia> Qx, x = QQ["x"];

julia> K, a = number_field(x^2 + x + 1, "a");

julia> M = matrix(K, 1, 1, [ a ]);

julia> G = matrix_group(M);

julia> order(G)
ERROR: Number field over Rational Field with defining polynomial x^2 + x + 1 is not a cyclotomic field
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _iso_oscar_gap(FO::AnticNumberField)
...
```

**Describe the solution you'd like**
Make this possible, if it is feasible. Especially since the number field above is exactly `CyclotomicField(3)`, OSCAR just doesn't know about it.

**Describe alternatives you've considered**
If this is not possible/feasible, provide a more informative error message, like "Group orders can only be computed over cyclotomic fields..." + possible information, how to solve the problem.

**Additional context**
I'm not sure how much of an "issue" this actually is since there will always be a big enough cyclotomic field for a given finite group. Feel free to close this issue, if you don't think it is relevant.

**Comment by fingolfin** [comment]
Thanks! It's a good suggestion

**Comment by fieker** [comment]
a pure gap-interface problem as this works:
```
julia> Oscar.isomorphic_group_over_finite_field(G)
(Matrix group of degree 1 over Finite field of degree 2 over F_5, Map from
G to Matrix group of degree 1 over Finite field of degree 2 over F_5 defined by a julia-function with inverse)
```
Same group as in the example above...

**Comment by joschmitt** [comment]
You are right!
The problem appears to be the access to `G.X` in `compute_order`.
```
julia> G.X
ERROR: Number field over Rational Field with defining polynomial x^2 + x + 1 is not a cyclotomic field
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] _iso_oscar_gap(FO::AnticNumberField)
    @ Oscar ~/.julia/dev/Oscar/src/GAP/iso_oscar_gap.jl:249
...
```

**Comment by fieker** [comment]
On Tue, Feb 14, 2023 at 06:05:28AM -0800, Johannes Schmitt wrote:
> You are right!
> The problem appears to be the access to `G.X` in `compute_order`.
> ```
> julia> G.X
> ERROR: Number field over Rational Field with defining polynomial x^2 + x + 1 is not a cyclotomic field
> Stacktrace:
>   [1] error(s::String)
>     @ Base ./error.jl:35
>   [2] _iso_oscar_gap(FO::AnticNumberField)
>     @ Oscar ~/.julia/dev/Oscar/src/GAP/iso_oscar_gap.jl:249
> ...
that should teach us to have complicated getproperty functions ...

**Comment by ThomasBreuer** [comment]
I am not sure whether I catch the point.

Currently Oscar's matrix groups claim to be able to delegate questions to underlying GAP groups.
For matrix groups that are defined over finite fields or over fields of cyclotomic type, the corresponding generating GAP matrices can be constructed via `Oscar._iso_oscar_gap`, this is what is tried in the `G.X` call.

For number fields that are not of cyclotomic type, there is currently no `Oscar._iso_oscar_gap` method. (We can provide such a method that translates field elements between Oscar and GAP.)

As Claus wrote, an alternative approach is to delegate questions to an isomorphic group over a finite field. This approach is in principle used in the `order` method for matrix groups over number fields (see `compute_order`), but the code in question wants to ask GAP whether the group on the GAP side obtained by `Oscar._iso_oscar_gap` would have nice enough properties such that it could be regarded as better than a matrix group over a finite field.
The problem is that currently the `Oscar._iso_oscar_gap` approach is not always supported.

Thus I think that we have to decide between the available strategies (switch to a matrix group in GAP via translating matrix entries, switch to a matrix group in Oscar over a finite field, switch to a group over the Rationals via blowing up the matrices, switch to something different) before asking GAP.
Once an appropriate isomorphism has been created for an Oscar matrix group, it should be stored as an attribute, and can be reused for other questions. This is similar to the "nice monomorphism" idea in GAP, but must live on the Oscar side, and the isomorphisms in question need not involve GAP.

**Comment by fingolfin** [comment]
This works now:
```
julia> Qx, x = QQ["x"];

julia> K, a = number_field(x^2 + x + 1, "a");

julia> M = matrix(K, 1, 1, [ a ]);

julia> G = matrix_group(M);

julia> order(G)
3
```
We also have a second approach to make it work that does not involved mapping elements but rather works by wrapping whole OSCAR matrices, there is a separate issue for that.
