### ISSUE TITLE
SLPoly (in Oscar) does not print

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#196]
julia> S = slpoly_ring(QQ, 2)
SLP Multivariate Polynomial Ring in x_1, x_2 over Rational Field

julia> gens(S)
2-element Array{Oscar.StraightLinePrograms.SLPoly{fmpq,Oscar.StraightLinePrograms.SLPolyRing{fmpq,FlintRationalField}},1}:
 Error showing value of type Array{Oscar.StraightLinePrograms.SLPoly{fmpq,Oscar.StraightLinePrograms.SLPolyRing{fmpq,FlintRationalField}},1}:
ERROR: MethodError: no method matching length(::Oscar.StraightLinePrograms.SLPoly{fmpq,Oscar.StraightLinePrograms.SLPolyRing{fmpq,FlintRationalField}})

why the Oscar.show is chosen over the SLP one, I don't know

**Comment by rfourquet** [comment]
> why the Oscar.show is chosen over the SLP one, I don't know

I think that's because AA defines `show` with three arguments, whereas SLP defines only the two arg version. And the REPL choses the 3-arg version if available... I don't think we should define `length` for `SLPoly` (it would practically mean converting to an `MPoly`), so I will just define the 3-arg `show` method.

**Comment by tthsqe12** [comment]
May I suggest that you implement expressify for your slps? Just build the expr and AA figures out the ()...
When thomfa and I were investigating the show function, we found that different show functions are called depending on the context.

**Comment by rfourquet** [comment]
> May I suggest that you implement expressify for your slps?

Good idea, I will do!

**Comment by rfourquet** [comment]
This can be closed.
