### ISSUE TITLE
Support mapping `quadratic_field` elements to GAP and back

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2049]
It would be great if we could support mapping elements of quadratic number fields to/from GAP. But the following right now gives an error:
```julia
F, sqrt3 = quadratic_field(3);
sigma = matrix(F, [1 0 0 ; 0 -1 0 ; 0 0 -1])
tau = matrix(F, [1//2 -sqrt3//2 0 ; sqrt3//2 1//2 0 ; 0 0 1])
G = matrix_group(sigma, tau)
order(G)
```
I guess we can just ask GAP to what element we should map the square root:
```
gap> Sqrt(3);
-E(12)^7+E(12)^11
```

Indeed, for now I can use this workaround:
```
F, z12 = CyclotomicField(12)
sqrt3 = sqrt(F(3))
```

**Comment by ThomasBreuer** [comment]
Is the question to define a default conversion between quadratic number fields in Oscar and quadratic subfields of cyclotomic fields in GAP, via `Oscar.iso_oscar_gap`?
On the one hand, GAP's support for quadratic number fields as subfields of cyclotomic fields is better than its support for number fields via `AlgebraicExtension`.
On the other hand, computations with square roots represented as cyclotomics are not efficient.

Do we want to offer both conversions for quadratic (and cyclotomic) fields in Oscar to GAP, with either an `AlgebraicExtension` field or a field of cyclotomics on the GAP side, perhaps via an optional argument with value `IsAlgebraicExtension` or `IsCyclotomicCollection`?

**Comment by fingolfin** [comment]
Honestly I don't care about the result as long as my example code above works. I guess on the long run we'd want that code to work by using `OscarMatrixObj` group elements on the GAP side, but as you know, we are still not there.

So, if you can rig something up to make that example work, I am fine no matter what it uses on the GAP side.

**Comment by fingolfin** [comment]
Actually, I take that back: of course there is the code by @danielrademacher in `experimental/Matrix/matrix.jl` and `experimental/Matrix/matrix.g` which *does* work by wrapping. And it seems to work in this example just fine:
```
julia> F, sqrt3 = quadratic_field(3);

julia> sigma = matrix(F, [1 0 0 ; 0 -1 0 ; 0 0 -1]);

julia> tau = matrix(F, [1//2 -sqrt3//2 0 ; sqrt3//2 1//2 0 ; 0 0 1]);

julia> G = Oscar.MatrixGroups.matrix_group(sigma,tau)
Matrix group of degree 3 over F

julia> order(G)
12
```

That leaves the question how to best make use of that code... I still think that for matrix groups over finite fields, we want to do what we are doing now.

But perhaps we could implement something like this: if we have a ring isomorphism between OSCAR and Julia, use that. If not, use Daniel's wrapping code. Thoughts?

**Comment by ThomasBreuer** [comment]
@fingolfin O.k., one step back.
With the current Oscar master, I do not get an error with the example shown above.
The matrix group `G` stores `G.ring_iso` with domain `F` and codomain an algebraic extension on the GAP side, which you propose to replace by a map with codomain a quadratic field of cyclotomics.
However, the `order(G)` call uses `Oscar.compute_order` which uses `Oscar.isomorphic_group_over_finite_field` because at this point `GAP.Globals.HasIsHandledByNiceMonomorphism(G.X)` is `false`, thus `G.X` is not used for the order computation.

For other computations than `order(G)`, we do not have such special code at the moment, that is, the task is delegated to `G.X`, and here the question arises what we want to use:
Currently `G.ring_iso` is almost always used to create GAP matrices by mapping the matrix entries (see the `getproperty` methods in `Groups/matrices/MatGrp.jl`).
As an alternative, we can wrap the given Oscar matrices on the GAP side, depending on `G.ring`. Perhaps we should allow the user to choose between the two possibilities, via an additional argument in the matrix group construction, then one can easily switch between the two variants, and compare the behaviour.

(For the moment, I will provide `Oscar.iso_oscar_gap` code for quadratic fields as discussed above.)

**Comment by fingolfin** [comment]
Indeed I was using OSCAR 0.11.3, so it's great that this is working on `master`. Probably your fix for #1930 resolved it?

**Comment by fingolfin** [comment]
So this works now, great! But it seems e.g. `natural_character` does not. Its docstring indicates that it only works over cyclotomics. Can we support this input, too? Right now I see this:
```
julia> F, sqrt3 = quadratic_field(3);

julia> sigma = matrix(F, [1 0 0 ; 0 -1 0 ; 0 0 -1]);

julia> tau = matrix(F, [1//2 -sqrt3//2 0 ; sqrt3//2 1//2 0 ; 0 0 1]);

julia> G = matrix_group(sigma, tau);

julia> natural_character(G)
ERROR: Error thrown by GAP: Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 3rd choice method found for `ConjugacyClasses' on 1 arguments at ...
```
I assume this is the same problem as in #2050. So let's compute the `order` to force a natural monomorphism, and then try again:
```
julia> order(G)
12

julia> natural_character(G)
ERROR: AssertionError: fl
Stacktrace:
 [1] (::QQAbField{AnticNumberField})(a::nf_elem)
   @ Oscar.GModuleFromGap ~/Projekte/OSCAR/Oscar.jl/experimental/GModule/GModule.jl:957
 [2] #1636
   @ ./none:0 [inlined]
 [3] iterate
   @ ./generator.jl:47 [inlined]
 [4] collect(itr::Base.Generator{Vector{GroupConjClass{MatrixGroup{nf_elem, AbstractAlgebra.Generic.MatSpaceElem{nf_elem}}, MatrixGroupElem{nf_elem, AbstractAlgebra.Generic.MatSpaceElem{nf_elem}}}}, Oscar.var"#1636#1637"{QQAbField{AnticNumberField}}})
   @ Base ./array.jl:782
 [5] natural_character(G::MatrixGroup{nf_elem, AbstractAlgebra.Generic.MatSpaceElem{nf_elem}})
   @ Oscar ~/Projekte/OSCAR/Oscar.jl/src/Groups/group_characters.jl:1122
 [6] top-level scope
   @ REPL[37]:1
```

**Comment by ThomasBreuer** [comment]
The question behind the `AssertionError: fl` is how natural a natural character is.
The square root of 3 is in a cyclotomic field, and we need an embedding into `QQAbField` in order to write down the character. Currently such a natural embedding is provided only for `nf_elem`s whose parents are of `Hecke.is_cyclotomic_type`, i.e., which have been created as cyclotomic fields.
We can define and implement such embeddings also for quadratic fields. For general abelian number fields, it will not be straightforward.

**Comment by ThomasBreuer** [comment]
@fingolfin The GAP error saying that no `ConjugacyClasses` method was found is due to the fact that currently the GAP matrices contain elements of an `AlgebraicExtension`. This problem should disappear when pull request #2056 gets merged.
Note that GAP installs many redispatch methods that check the finiteness of the group, but only for matrix groups over cyclotomics, not for matrix groups over an `AlgebraicExtension`.
