### ISSUE TITLE
enhancing JuLie imports

### ISSUE THREAD

**Issue by micjoswig** [oscar-system/Oscar.jl#2057]
The documentation, e.g., of the `Partition` type refers to Wikipedia.  I would like to suggest to change this to a proper math book reference, e.g., Fulton: Young Tableaux.

The function `ascending_partitions` takes `alg` as an optional argument, which is a string.  Please convert this to a symbol.  Comparing symbols, to check which algorithm the user prefers, is faster than comparing strings.

@ulthiel @lkastner @ClaudiaHeYun

**Comment by ulthiel** [comment]
I can take care of updating the documentation. As I've noted somewhere else already, ascending_partitions should better be ascending_compositions (because it's not a partition technically). There should be a type Compositions (and elsewhere I have implemented fast generators for compositions that I will (try to) check into OSCAR eventually).

**Comment by fingolfin** [comment]
I also note that some places use `alg` and some use `algo`. We should settle on one common name. Either one of those, or something new like `algorithm`, which arguably would fit better with our goal of self-explaining names, but would also be more tedious to type; since this is an option for specialists, I am happy to keep it short. Since `alg` could also stand for `algebra`, I propose we settle on `algo`. But I am happy with something else, too.

**Comment by HechtiDerLachs** [comment]
The issue about the unsatisfactory contribution to the style guide can now be addressed here: #2084 .

**Comment by micjoswig** [comment]
Thanks!!!
