### ISSUE TITLE
Structure in experimental

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#2146]
I already talked about this to @fingolfin and @HereAround . The folder structure for experimental stuff is a bit confusing. There is `experimental` for source code, separate from `src`, while `test/Experimental` contains the tests and `docs/src/Experimental` contains the docs. Max proposed the following structure, which I like very much (if it is possible):
```
experimental/PACKAGE/{src,test,docs}
```
Then one could still have `experimental/test.jl` and `experimental/experimental.jl` for the code inclusions, not sure about the docs. In case there is not too much discussion, I would go ahead and implement these things in the lie algebra PRs #2145 and #2115, of course while coordinating with the respective authors. I don't think it is necessary to change this for the remaining things, but I'd also adapt the developer docs and then the old style should slowly fade out.

Maybe this also makes things easier for #2011.

**Comment by fingolfin** [comment]
Yeah so the directory tree would look like this:
```
experimental/
├── ExteriorAlgebra
│   ├── README.md
│   ├── docs
│   │   └── intro.md
│   ├── src
│   │   └── main.jl
│   └── test
│       └── runtests.jl
├── GaloisGrp
│   ├── README.md
│   ├── docs
│   │   └── intro.md
│   ├── src
│   │   └── main.jl
│   └── test
│       └── runtests.jl
:
├── experimental.jl
└── runtests.jl
```
Of course there could be more files in each of the subdirs. 

The content of `experimental/experimental.jl` could be just this:
```julia
import Glob   # just to keep this short, obviously we can also do it "by hand"
for fname in Glob.glob("*/src/main.jl")
  include(fname)
end
```
or if that's too "automagic", of course also this is fine:
```julia
include("ExteriorAlgebra/src/main.jl")
include("GaloisGrp/src/main.jl")
```

Similar for `runtests.jl`.

My main concern is whether and how this will work with the documentation, so that's the first thing I'd try experimentally: change `docs/doc.main` to refernece a file outside the `docs` dir, using `..`

**Comment by fingolfin** [comment]
And then next, how to add those files into the manual... right now we hook some of them into various parts of the hierarchy, manually. We can of course continue this, it's fine. Though I note that there are a few "orphaned" files in `docs/src/Experimental`, e.g. `docs/src/Experimental/Singularities/space_germs.md` (I realize this may be intentional, it's just hard to know w/o digging into git logs or asking the right people)

**Comment by lkastner** [comment]
For the manual  I wanted to go with your proposal from #2011 and introduce an `experimental` section.
