### ISSUE TITLE
Leftovers from #2157 in `docs/src/Experimental/`

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2189]
In `/docs/src/Experimental/`, there are some files about curves `{divisors,elliptic_curves,introduction,non_plane_curves}.md`. I suppose, they have been forgotten in #2157 when turning `PlaneCurve` into the new `experimental` structure.

cc @lkastner

**Comment by lkastner** [comment]
Probably. It was really unclear to me what to do with these, since the corresponding lines in `docs/doc.main`
https://github.com/oscar-system/Oscar.jl/blob/master/docs/doc.main#L188 are commented out. The `plane_curve.md` was also commented out. So I am really not sure what to do about this. I can move these, but are they needed?
`git blame docs/doc.main` gives:
```
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 188)      "Curves" => [
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 189) #        "Experimental/introduction.md",
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 190) #        "Experimental/plane_curves.md",
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 191) #        "Experimental/divisors.md",
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 192) #        "Experimental/elliptic_curves.md",
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 193) #        "Experimental/non_plane_curves.md",
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 194)          "AlgebraicGeometry/Curves/para_rational_curves.md",
6d0cd7c2343 (Martin Bies          2022-10-31 12:19:20 +0100 195)      ],
```
and `git show 6d0cd7c2343` simply says
```
commit 6d0cd7c2343c64bca9d6698dd1c7950cf9f94be3
Author: Martin Bies <HereAround@users.noreply.github.com>
Date:   Mon Oct 31 12:19:20 2022 +0100

    Schemes: Add documentation for affine schemes
```
So maybe @HereAround can help us out?

**Comment by HereAround** [comment]
I have just compared 

```
commit 6d0cd7c2343c64bca9d6698dd1c7950cf9f94be3
Author: Martin Bies <HereAround@users.noreply.github.com>
Date:   Mon Oct 31 12:19:20 2022 +0100
```
with the preceeding:
```
commit 0eed8fbdd990cf4f3e488e3dc58b24cd988e00ec
Author: Martin Bies <MBies87@googlemail.com>
Date:   Mon Oct 31 12:18:00 2022 +0100

    Schemes: Code improvement
    - Fix minor typos
    - Add display method for morphisms of affine schemes
    - Improve equality of affine schemes
    
    Co-authored-by: Matthias Zach <HechtiDerLachs@users.noreply.github.com>
```
It is true, that I touched the above mentioned lines in `6d0cd7c2343c64bca9d6698dd1c7950cf9f94be3`, but only because I reorganized the code in `docs/doc.main`. Crucially though, those lines were already outcommented before my commit.

Still, I believe I can provide a minor pointer. Namely, unless I am mistaken, this code was added by a former student of @wdecker. As of our last conversation, changes to this code will be needed before it can be moved into `/src`. Presumably, this is the reason why the corresponding documentation was outcommented. Maybe @wdecker can elaborate more.

**Comment by lgoettgens** [comment]
Thanks for your exploration. 
If there is more work to be done on this, I would suggest keeping the auxiliary doc files with the main one in `experimental/PlaneCurve/docs/src`, and moving the commented-out part into the experimental `doc.main` (keeping it commented out to not change the deployed docs).
This would tidy `docs/src/Experimental/` a bit up. In the future, this problem of lost track will eventually come up again, and we could circumvent that now.

**Comment by fingolfin** [comment]
I was not aware of this issue when I made PR #2197, but that PR basically addresses this issue.
