### ISSUE TITLE
Cone constructor to construct cones from inequalities and equations

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#2218]
**Is your feature request related to a problem? Please describe.**
Unlike `polyhedron`, `cone` seems to have no constructor that constructs it from inequalities:
https://docs.oscar-system.org/stable/PolyhedralGeometry/Polyhedra/constructions/
https://docs.oscar-system.org/stable/PolyhedralGeometry/cones/#Construction

It would be nice if such a constructor exists. I'm currently using the following code to construct a cone from inequalities in my Groebner fan code:
```
rays(polarize(positive_hull([1 1; 0 1])))
```

It seems to work even though `polarize` is only documented for `Polyhedron`:
https://docs.oscar-system.org/stable/PolyhedralGeometry/Polyhedra/auxiliary/#polarize-Union{Tuple{Polyhedron{T}},%20Tuple{T}}%20where%20T%3C:Union{Float64,%20fmpq,%20nf_elem}

**Describe the solution you'd like**
`Cone(A,B)` to construct the cone {A*x>=0, B*x=0} would be great.

**Comment by alexej-jordan** [comment]
There actually is a function `cone_from_inequalities` that does exactly that. Unfortunately, its docstring has not been included in our docs yet, so i will do that. You can still ask for that docstring using `julia`'s help mode until then.

On another side note, this function always expects at least one inequality. If this is a problem for you we can work out a solution (possibly a function `cone_from_equations`).

**Comment by YueRen** [comment]
Thanks, `cone_from_inequalities` is significantly faster than my `polarize(positive_hull())` workaround!

Two questions, are the following intended behaviour?
1. `cone_from_inequalities` gives me an error when I give him a matrix with a zero row.
2. `cone_from_inequalities` works fine with `fmpq_mat`, but struggles with other input types like `Vector{Vector{Int}}`.

**Comment by alexej-jordan** [comment]
Happy to help! To answer your questions:

1. This error roots directly in polymake and is intended because we do not want to allow a zero vector as an input. I guess we could filter out these rows automatically in the case these are results of some (unpredicted) computations. If you are trying to circumvent the limitation that we have to name the inequalities, my previous answer was a bit imprecise: the first argument is necessary but it can be "empty". You can achieve this by constructing a matrix with `0` rows and `d` entries, where `d` is the corresponding ambient dimension:
```
Matrix{Int}(undef, 0, d)
```

2. In the introduction of the docs for polyhedral geometry there is a section about different input formats: https://docs.oscar-system.org/stable/PolyhedralGeometry/intro/#Halfspaces-and-Hyperplanes
For now we do not support vectors over vectors to describe hyperplanes/halfspaces, but this sounds like a meaningful description and it should be no problem to extend our capabilities here.

**Comment by YueRen** [comment]
I will close this issue since jordan's pull request has been merged. Thanks a lot!
