### ISSUE TITLE
Make minimal_generating_set consistent

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#2295]
@HechtiDerLachs Please make sure that the function computing minimal generating sets for ideals in local rings fits to what comes out of PR #2291 (this applies in particular to the name of the function).

**Comment by HechtiDerLachs** [comment]
The code in `src/Rings/mpoly-local.jl` is deprecated. Instead of adjusting it, we should discuss about finally removing that file so that not even more work is put into these 'old' local rings and their ideals. We can then eventually add the method with the new correct name for the respective new localizations.

**Comment by wdecker** [comment]
I agree.

**Comment by fingolfin** [comment]
@HechtiDerLachs what is the status of this?

**Comment by afkafkafk13** [comment]
fixed with PR #2545
