### ISSUE TITLE
Semantic conflict between `gens(U::PrincipalOpenSubset)` and `getindex(U::PrincipalOpenSubset, i::Int)`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#2324]
Consider these methods:
```julia
gens(U::PrincipalOpenSubset) = [lifted_numerator(complement_equation(U))]
ngens(U::PrincipalOpenSubset) = 1
getindex(U::PrincipalOpenSubset, i::Int) = (i == 1 ? U : error("index out of range"))
```

Normally for most types, we'd expect `gens(U)[i] == U[i]`.

In fact we'd expect both to be equal to `gen(U, i)` which however not exist here. I wanted to add one, but the above contradiction doesn't allow it, esp. in light of https://github.com/Nemocas/AbstractAlgebra.jl/pull/1332 where we want to make the equality `gen(X,i) = X[i]` universal for all parent objects.

**Comment by fingolfin** [comment]
I think this code may be by @HechtiDerLachs so he might be best qualified to say what should be done.

**Comment by fieker** [comment]
On Thu, Apr 27, 2023 at 12:12:38AM -0700, Max Horn wrote:
> I think this code may be by @HechtiDerLachs so he might be best qualified to say what should be done.
> 
I talked to him, a silly mistake

**Comment by HechtiDerLachs** [comment]
Sorry, it turns out to not be so easy. The failure of the tests in my PR made me remember. 

The origin lays in the `SpecOpen`s. Any such `SpecOpen` `U` in `X` is covered by affine open subsets `V_1,..., V_n` which are principally open in `X`, i.e. `V_i = X \cap {f_i != 0}`. Now `gens(U)` was referring to the list of the `f_i`s, while `getindex` was supposed to return corresponding entry of the list of `V_i`s. 

So you say you wanted to make this coherent throughout Oscar starting from within Nemo? Then we do have a conflict here. I suggest to talk in person about how to resolve this.

**Comment by afkafkafk13** [comment]
@HechtiDerLachs: Would we even consider calling the complement equation of a principal open subset a generator in the mathematical sense? Maybe the root of this semantic conflict is a bad choice of name? 
(On the commutative algebra side, we are talking about the generator f of a multiplicatively closed set of type {f^i | i \in NN} used for localization, on the geometric side this is the equation of the complement of the given principal open set. So both not really situations in which you would talk about generators.) Maybe just not calling it gens, would be an option. But what would be a good name for it?
 
The getindex on the other hand makes sense as it is, as it returns the i-th patch of the covering from which the SpecOpen has originally been constructed.
