### ISSUE TITLE
Static testing and `test/Project.toml` for *all* packages

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/Oscar.jl#2385]
This is a checklist to implement the changes proposed in #1964 and #2374 for `Oscar.jl` to be done similarly in the other packages.

Move test dependencies from `Project.toml`'s `[extra]` to `test/Project.toml` (#2374)

- [x] Oscar.jl: #2386
- [x] AbstractAlgebra.jl: https://github.com/Nemocas/AbstractAlgebra.jl/pull/1363
- [x] GAP.jl: https://github.com/oscar-system/GAP.jl/pull/882
- [x] Hecke.jl: https://github.com/thofma/Hecke.jl/pull/1078
- [x] Nemo.jl: https://github.com/Nemocas/Nemo.jl/pull/1476
- [x] Polymake.jl: https://github.com/oscar-system/Polymake.jl/pull/435
- [x] Singular.jl: https://github.com/oscar-system/Singular.jl/pull/649

Add Aqua.jl for some static testing (#1964/#2370)
- [x] Oscar.jl: #2370
- [x] AbstractAlgebra.jl: https://github.com/Nemocas/AbstractAlgebra.jl/pull/1366
- [x] GAP.jl: https://github.com/oscar-system/GAP.jl/pull/883
- [x] Hecke.jl: https://github.com/thofma/Hecke.jl/pull/1086
- [x] Nemo.jl: https://github.com/Nemocas/Nemo.jl/pull/1485
- [x] Polymake.jl: https://github.com/oscar-system/Polymake.jl/pull/437
- [x] Singular.jl: https://github.com/oscar-system/Singular.jl/pull/652

fix `stale_deps` check by Aqua.jl once https://github.com/JuliaTesting/Aqua.jl/pull/113 is available
- [x] Oscar.jl: https://github.com/oscar-system/Oscar.jl/pull/2440
- [x] GAP.jl: https://github.com/oscar-system/GAP.jl/pull/887

**Comment by fingolfin** [comment]
Just as a heads-up, the "weird error with GAP_lib_jll" in the `stale_deps` check by Aqua.jl is caused by the GAP package Browse printing a \r character upon initialization (see also https://github.com/gap-system/gap/issues/430 ; ping @ThomasBreuer). Unfortunately I currently know no way to avoid that. So instead I submitted https://github.com/JuliaTesting/Aqua.jl/pull/113 to make Aqua more robust.
