### ISSUE TITLE
Weird probably broken syntax in `degree()`

### ISSUE THREAD

**Issue by c42f** [oscar-system/Oscar.jl#2452]
The following line contains some weird, probably unintentional syntax:

https://github.com/oscar-system/Oscar.jl/blob/b54882061f676c5ea6dd23a32f6b5d3c86e63442/src/Modules/ModulesGraded.jl#L522

I noticed this over at https://github.com/JuliaLang/julia/pull/46372 where I'm testing the entire General registry.

The syntax on that line probably doesn't do what you expect or want:

```julia
julia> Meta.parse("""d = degree(f)isa(f.d, GrpAbFinGenElem) || error("The specified element is not homogeneous.")""")
:(d = degree(f) * (f.d isa GrpAbFinGenElem) || error("The specified element is not homogeneous."))
```

**Comment by fingolfin** [comment]
Thank you for this report!

Looks like a newline was somehow accidentally deleted, and nobody noticed because by chance the code still works correctly unless `f` has degree 0 (because either the `isa` test passes, and we multiple by `true == 1`, so `d` is not changed, and if `d` is non-zero we also don't invoke `error`; or the `isa` test fails, then we multiple by `false == 0`, the result of which is also `false == 0`, so the error is raised).

So of course we should fix this. But in addition this suggest that a few more tests for this function covering various corner cases would be nice to have.

**Comment by c42f** [comment]
Haha!  I wondered if something like this might be going on with multiplying by the bool.  It's amazing that this code - as bizarre as the parsing is - actually worked.

**Comment by c42f** [comment]
Mostly worked, that is :laughing:
