### ISSUE TITLE
Schur multiplier for groups

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#2962]
Would be great if we could have a `schur_multiplier` function, which could be implemented via `AbelianInvariantsMultiplier` from GAP. For my own usage, I would be happy if this returns (per default) an ordinary abelian group. Maybe we could add an optional type for the return value, as we do for other such constructions.

I am not a group theorist and not married to the name, but I think it is perfect.

Any thoughts @fingolfin @ThomasBreuer?

**Comment by ThomasBreuer** [comment]
No objections, in particular the name `schur_multiplier` is o.k.

I will provide a pull request for this issue.

Concerning GAP's `AbelianInvariantsMultiplier`:
The documentation says that this works well for pcp groups (from the Polycyclic package) due to a special method for these groups, but that the generic method (which computes in fact a Schur cover),  does not perform well for larger groups.
Furthermore, there is a hint that one could use to Cohomolo package for larger groups; this would mean to compute each p-part of the multiplier separately, and then to combine these results.
As soon as such problems arise in Oscar, we can either follow this hint or try something better.

**Comment by thofma** [comment]
My groups are small, so I did not notice the performance problems for larger groups. I agree with your assessment. Thanks for taking a look at this.
