### ISSUE TITLE
Should there be a copyright/license notice at the top of every source file?

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#310]
It is recommended [here](https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile) by the gnu people. I have seen this in many open source projects. Apologies if this has been discussed before.

**Comment by lkastner** [comment]
Apparently some geo people had [issues](https://github.com/fatiando/maintenance/issues/10) that they thought could be solved by having included such a notice. This is of course not statistically relevant.

**Comment by thofma** [comment]
Sounds like a good idea.

**Comment by fingolfin** [comment]
This is *very slightly* useful in *some* jurisdictions, but not in many others; it makes it tad harder for violators of the GPL to claim they copied code from a file but were mistaken about the license for that file.

So, this is mostly important if we are concerned that people are going to take our code and use it in non-GPL projects. And then it can make it easier to proof that the offender must have known what they were doing.

However, note that the offender would actually have to prove that they had reasonable grounds to expect the code to be public domain or under a different license; otherwise, they would not be allowed to use the code anyway, regardless of how we license it (caveat: details depend greatly on the jurisdiction).

So this is all about shifting probabilities in the end, *in case of legal proceedings*. If you don't expect people to misappropriate our code and hire a lawyer over it, it has zero use.

Anyway, I don't mind a legal header, as long as they are not dumb, and can stay static. Dumb headers include those which have a copyright year / year range. In the US jurisdiction, AFAIK this is required for valid copyright line ("copyright (C) 2020 Max Horn") at least in order to be able to proof that your copyright is not expired. However, for us the age of the project plus git commit history are easily sufficient to establish this. The drawback of these years is that people tend to do huge "let's update all copyright years" commits touching all source files every other year, which is distracting and actually can be harmful to the main point of the copyright notice (to establish the time extent of your copyright claim), as copyright only is granted if you actually do something copyrightable in that year; so by mass updating this, you actually weaken the plausibility of this.

For GAP, we arrived at legal headers of this form:
```
/****************************************************************************
**
**  This file is part of GAP, a system for computational discrete algebra.
**
**  Copyright of GAP belongs to its developers, whose names are too numerous
**  to list here. Please refer to the COPYRIGHT file for details.
**
**  SPDX-License-Identifier: GPL-2.0-or-later
```

This establishes the provenance of the code (i.e., part of GAP); the license (in a machine readable format, so that tools big companies employ for compliance testing can determine it automatically; also GitHub uses this); and the information that someone has a copyright claim, with detailed information in a single separate place.

This should be sufficient for the main purpose of these legal headers (see above). But of course IANAL, if anybody is really concerned about this, we need to hire an actual lawyer specialized on this (or actually multiple ones, one for each jurisdiction we worry about) to check this / give us advise. But IMHO this is absolutely not necessary.

Source for much of this: In 2009 I retained a lawyer for resolving a GPL violation against a big gaming company (I am not allowed to talk about it, but you can use google...). As typical in these cases, it was settled out of court; the source file all had copyright headers, but this had zero relevance. Involved parties were (at least) in the US, Canada, Germany and Ukraine. I had to read up a lot on this and had discussions with the lawyer, and learned more about this shit than I ever cared about. *sigh* We did have copyright headers back then, by then, they had exactly zero impact.
