### ISSUE TITLE
ordering of `MPolyQuoRing`

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#3102]
It should NOT be allowed to change the ordering of a `MPolyQuoRing`:

julia> B, _ = quo(S, ideal(S, [x^2*z-y^3, x-y]), ordering = lex(R));

julia> B.ordering = degrevlex(R);

julia> B.ordering
degrevlex([x, y])

Any ideas?

**Comment by lgoettgens** [comment]
We cannot disable modifying the fields of a struct (without making the whole struct immutable). But modification of fields is not allowed for users and can lead to unexpected / wrong results.

**Comment by thofma** [comment]
Any field (the things accessed via `.`) in most objects can be changed in that way. This is not something special about orderings. You can even change the coefficient ring of a polynomial ring this way.

Starting with julia 1.8, one can mark specific fields as `const`, which we should use and which would help with Wolfram's example. It will not help with everything, since we need some fields to be mutable for the functions to modify or update them. But this will only be an option, once we increase the minimal julia version we support for Oscar master.

P.S.: For the `const` thingy see https://docs.julialang.org/en/v1.11-dev/manual/types/#Mutable-Composite-Types
