### ISSUE TITLE
Add build option for ASCII/non-ASCII chars

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Oscar.jl#318]
In the following discussion we decided that Nemo/AbstractAlgebra will ban use of non-ASCII characters:

https://github.com/Nemocas/Nemo.jl/issues/1013

During that discussion @kalmark had the recollection that we decided we were going to add a global switch to allow/disallow non-ASCII chars for Oscar and dependencies. This would fix the issue for users, though I believe it will not fix the issue for developers reading code (e.g. from old versions of Windows console) containing such chars, depending how it is implemented.

Therefore a decision needs to be made if:

1) The no-ASCII ban will hold across all Oscar repos; or
2) We implement a global switch

**Comment by micjoswig** [comment]
A discussion at the OSCAR meeting today suggested that a global switch is desirable. Please investigate if this is feasible. What does it take?

**Comment by wbhart** [comment]
I presume the discussion today was in relation to printing non-ASCII characters in output (i.e. printing). If so, then I think @tthsqe12 has to comment on this.

Of course I don't know of any way to implement a switch so that people will see non-ASCII characters in code in the repository. But I assume that wasn't being suggested.

**Comment by tthsqe12** [comment]
I don't think this related directly to the printing code, since the printer doesn't generate non-ascii unicode unless given such input.
- If the goal is the have the printer churn out `zeta` when it sees `ζ`, then indeed this is a printer issue. However,
- It seems more reasonable to have the global switch simply mean that internally we promise to use 'z' as the variable name instead of `ζ` when then flag is set to true.

**Comment by wbhart** [comment]
So this would be about default variable names?

**Comment by thofma** [comment]
Yes. Or if someone wants to print "→" instead of "->".

**Comment by micjoswig** [comment]
I am not sure, but is this helpful?

https://docs.julialang.org/en/v1/base/strings/#Base.transcode

Maybe the global switch could force each `show` to go through such a transcoding?

**Comment by thofma** [comment]
Unfortunately not. 

Here is my suggestion:

1. Have a `Oscar.get_unicode_output()` (or whatever name we come up with), which returns `true` if we are allowed to output Unicode and `false` otherwise.
2. It will be the responsibility of the implementor of the `show` method to respect this setting.
3. On the user-facing side we will have a `Oscar.set_unicode_output(::Bool)`.

I think there are too many choices to do some automatic "deunicoding" or "unicoding".

Happy to give the implementation a try if we are happy with this approach.

CC: @tthsqe12 @fieker @fingolfin

**Comment by micjoswig** [comment]
Makes sense to me.  Probably, the default should be to set `Oscar.set_unicode_output(::Bool)` to false then.

**Comment by thofma** [comment]
I am happy to implement it, but so far none of the others showed any sign of agreement/disagreement :)

**Comment by fingolfin** [comment]
We could use https://github.com/JuliaPackaging/Preferences.jl to allow the user to configure this

**Comment by fingolfin** [comment]
Anyway, what @thofma wrote is fine by me.

**Comment by fingolfin** [comment]
@fieker also expressed agreement orally just now

**Comment by tthsqe12** [comment]
I like it because it doesn't involve changing any of the AA pretty printing code.

**Comment by ThomasBreuer** [comment]
Fine. As soon as the global switch is available, I will change the code which I wrote such that only allowed characters are used.
