### ISSUE TITLE
Equality check and hashing for module orderings is broken

### ISSUE THREAD

**Issue by HechtiDerLachs** [oscar-system/Oscar.jl#3347]
I just witnessed this on the latest master (commit a0913ed719ece74a890e19120670cd79dbffc3aa):
```
julia> R, (x,y,z,w) = polynomial_ring(GF(32003), ["x", "y", "z", "w"]);

julia> F = FreeMod(R, 2)
Free module of rank 2 over Multivariate polynomial ring in 4 variables over GF(32003)

julia> o = lex(gens(F))*lex(gens(R))
lex([gen(1), gen(2)])*lex([x, y, z, w])

julia> oo = lex(gens(F))*lex(gens(R))
lex([gen(1), gen(2)])*lex([x, y, z, w])

julia> o == oo
false

julia> hash(o) == hash(oo)
false
```
It is not clear to me whether this is a recent regression or whether this has always been an issue. In any case, this is a serious problem, because caching of Groebner bases does not work. We should probably fix this soon.

CC: @jankoboehm , @wdecker

**Comment by fingolfin** [comment]
This seems to be a case of no `==` or `hash` methods defined for `ModuleOrdering`, so someone "just" needs to add them.

**Comment by HechtiDerLachs** [comment]
I agree. But it is not clear to me whether this is the case because it has never been there, or because it has been lost (e.g. due to a faulty merge or rebase). So I think those, who have worked on it, should have a look first. 

If it turns out that this has never been there, indeed, some experts should decide how to implement `==` check and hashing (probably in parallel with what's already there for monomial orderings?). I have too little insight on how all this might interfere with existing infrastructure. I just saw the current implementation cluttering my memory because of 120 Groebner basis computations triggered by 120 `is_zero` checks on elements of the very same module.

**Comment by fingolfin** [comment]
@HechtiDerLachs but who are these "experts" who should look at this? The original authors (Bill, Dan) are not active with us anymore... There might be others who worked on this recently, but who? And unless we ping them explicitly and ask them to look into this, I am pretty sure won't happen.

The one 

In the end someone may have to bit the bullet and just dig into this code.

I just had a quick look and it seems to me that type `ModuleOrdering` needs a similar treatment to `MonomialOrdering`: there we have a `canonical_matrix` method the result of which is cached, and which is used to define equality and a hash function.


In general that code in `src/Rings/orderings.jl` could benefit from some care and added comments. I find it a bit bewildering:
- what is the difference between `ModOrdering{T}` and `ModuleOrdering{S}`?
  - my guess is that the latter is the truly user facing type; the other is for internal use only? but I am not sure, nor do I know why both are needed
- what types are `T` and `S` standing in for?
- why is one a subtype of `AbsModOrdering` but the other is not?
- since `AbsGenOrdering` is the supertype for monomial orderings, why isn't it call `AbsMonOrdering` ?
- what is this mysterious comment trying to tell me (I am too dense, I am afraid)
```julia
# Module orderings (not module Orderings)
```

As far as

**Comment by joschmitt** [comment]
(Regarding the last point: `Module orderings (not module Orderings)` is a pun on the fact that we have a module named `Orderings` in which this file lives as far as I can see.)

**Comment by RafaelDavidMohr** [comment]
@ederc and me will take a look at it and fix the hashing/equality.
