### ISSUE TITLE
general_linear_group inputs

### ISSUE THREAD

**Issue by antonydellavecchia** [oscar-system/Oscar.jl#3361]
Currently in src/Groups/MatGrp.jl starting on line 587

we have 
```
function general_linear_group(n::Int, R::Ring)
   G = matrix_group(R, n)
   G.descr = :GL
   return G
end

function general_linear_group(n::Int, q::Int)
   return general_linear_group(n, _field_from_q(q))
end
```

I believe it makes sense to switch the arguments to be more consistent with the rest of 
Oscar, where the first input should be the field, ring , etc.. Similarly with the special_linear_group

```
function special_linear_group(n::Int, R::Ring)
   G = matrix_group(R, n)
   G.descr = :SL
   return G
end

function special_linear_group(n::Int, q::Int)
   return special_linear_group(n, _field_from_q(q))
end
```

and orthogonal_group, sympletic_group...

Is this something we want to change for Oscar 1.0?

**Comment by fingolfin** [comment]
It would however be highly inconsistent with any other system in this area (GAP, Magma), and also with common mathematical notation (there are countless books and papers using the `SL(n,q)` convention.

I am not convinced that group constructors benefit from being "similar" in this regard to ring or field constructors. They live in a completely different category after all. 

The best argument for a change would be perhaps the argument order for `matrix` which is why we allow both orders for `matrix_group`; but that's different because you can't specify the field via its size there, so supporting both orders introduces no ambiguity and so is fine.
