### ISSUE TITLE
vector_space_dimension returning infinity instead of throwing an error

### ISSUE THREAD

**Issue by Syz-MS** [oscar-system/Oscar.jl#3510]
**Is your feature request related to a problem? Please describe.**
Working with vector_space_dimension can be annoing since it throws an error exception in the infinite dimensional case. 
You always have to treat the infinite dimensional case separately, even if it would not be nessesary like for example if you want to check if two MPolyQuoRings have the same vector space dimension.  When doing simple things like that you could easily forget to treat the infinite dimensional case at all.

**Describe the solution you'd like**
 vector_space_dimension(A::MPolyQuoRing)  should in my opinion return infinity instead of throwing an error exception if A is a infinite dimensional vectorspace.

**Describe alternatives you've considered**
A minimal solution would be to provide a function is_finite_dimensional_vector_space().

**Comment by fingolfin** [comment]
For infinite dimensional cases, not that two infinite dimensional vector spaces still need not have equal dimension (though we could of course e.g. prescribe that we only ever support countable dimensions to resolve this...)

For endusers having `infinity` as a return value probably is most natural... The downside is that code which uses `vector_space_dimension` but does not explicitly handle the infinite case will be slower as Julia cannot deduce the type of the dimension.

For groups we decided against having `order` return a value indicating `infinity` (though that's what GAP does). However that is not necessarily the final word (we've even been thinking about extending `ZZRingElem` to allow encoding "infinity"...)... But it is what we have there right now, with the expectation that code that needs to deal with infinite groups has to first check for `isfinite(G)` before calling `order(G)`.

That would suggest to use a similar approach here.

A crucial part of this is that one should be able to distinguish an "infinite order" exception from an exception caused by a different problem. This is why we have a `InfiniteOrderError` type:
```
function order(::Type{T}, x::Union{GAPGroupElem, GAPGroup}) where T <: IntegerUnion
   ord = GAPWrap.Order(x.X)
   if ord === GAP.Globals.infinity
      throw(InfiniteOrderError(x))
   end
   return T(ord)
end
```

We could add a similar `InfiniteDimensionError` type.

**Comment by fingolfin** [comment]
The one thing to watch out is that `is_finite_dimensional_vector_space` should cache intermediate results to avoid making the combo `is_finite_dimensional_vector_space` followed by `vector_space_dimension` much slower than just `vector_space_dimension` alone. But I am told this is the case here, so we are fine.
