### ISSUE TITLE
Missing unary operators: `no method matching +(::AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQMPolyRingElem})`

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#3538]
Thanks again @benlorenz for clearing some of my confusion.

OSCAR (or maybe AbstractAlgebra) is missing some unary operators such as:
```
R,(k1,k2,k3,k4,k5,k6,k7,k8,cAC,cBD) = rational_function_field(QQ,["k1","k2","k3","k4","k5","k6","k7","k8","cAC","cBD"]);
S,(xA,xB,xC,xD) = R["xA","xB","xC","xD"]
+k3*xC*xD
```

which raises following error:
```
julia> +k3*xC*xD
ERROR: MethodError: no method matching +(::AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQMPolyRingElem})
```

I stumbled upon it when I tried to format some of my polynomial vectors for better visibility:
```
steadyStateEqs = [ -k1*xA*xB +k5*xB*xC +k3*xC*xD -k7*xD*xA ]
```

or

```
steadyStateEqs = [ -k1*xA*xB + k5*xB*xC + k3*xC*xD - k7*xD*xA, 
                   -k4*xA*xB - k2*xB*xC + k6*xC*xD + k8*xD*xA,
                   +k1*xA*xB - k5*xB*xC - k3*xC*xD + k7*xD*xA,
                   +k4*xA*xB + k2*xB*xC - k6*xC*xD - k8*xD*xA ]
```

**Comment by joschmitt** [comment]
Am I missing something or can we just add
```
+(x::NCRingElem) = x
```
in AbstractAlgebra?

**Comment by lgoettgens** [comment]
> Am I missing something or can we just add
> 
> ```
> +(x::NCRingElem) = x
> ```
> 
> in AbstractAlgebra?

Yes, exactly what I thought. See https://github.com/Nemocas/AbstractAlgebra.jl/pull/1640

**Comment by fingolfin** [comment]
Downside of unary +: it masks issues (as was the case here). Upsides of unary +: consistency (?)... but is it actually used in practice?

**Comment by YueRen** [comment]
What is the issue that was masked here?

**Comment by fingolfin** [comment]
Issues that are masked:  when creating vector and matrices, whitespace matters:
```
julia> [ 1 + 1 ]
1-element Vector{Int64}:
 2

julia> [ 1 +1 ]
1×2 Matrix{Int64}:
 1  1
```
It is very easy to mix these two up (IMHO that's a misfeature of Julia, but it is what it is, no point in arguing about it).

In contrast:
```
julia> [ e + e ]
1-element Vector{ZZRingElem}:
 2

julia> [ e +e ]
ERROR: MethodError: no method matching +(::ZZRingElem)
```
and arguably the second error can be helpful. Unless you *really* wanted the unary plus (but why? If it is to align things, you could just use extra spaces?)


@hannes14 points out that it can appear if one copies output from other system which uses unary plus. OK fine by me.


(I think overall I tend to say let's do unary plus because it is consistent with Julia, but my point here is that it is universally clear that it is an improvement...)

**Comment by YueRen** [comment]
Ah got it now.  Yes, the difference between `[ 1 + 1 ]` and `[ 1 +1 ]` is unfortunate.
