### ISSUE TITLE
gens for GL

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#3634]
```
julia> G
GL(3,QQ)

julia> G[1]
ERROR: Error thrown by GAP: Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `GeneralLinearGroupCons' on 3 arguments at /home/fieker/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/lib/methsel2.g:249 called from
GeneralLinearGroupCons( IsMatrixGroup, arg[1], arg[2] ) at /home/fieker/.julia/artifacts/b5c2f0f824457e5c391fb24916f94d5d91c62c4f/share/gap/grp/classic.gd:159 called from
<function "GeneralLinearGroup">( <arguments> )
 called from read-eval loop at *defin*:0

```

I understand that for a general `GL` we don't know gens, but maybe we could indicate a better error message?

**Comment by fingolfin** [comment]
Fair enough. We should print an error like "Error, this group is no finitely generated" and also makes sure `is_finitely_generated` returns true for `GL(n,k)` whenever `k` is an infinite field.

In general `gens(GL(n,R))` for a commutative ring `R` could print something like `Error, no generators known` (whether it is finitely generated may be difficult to decide in general. we can of course try to add support for more cases, e.g. if `R` is an order in a number field, but that's a different feature request then)

**Comment by fingolfin** [comment]
(and of course the same for `SL` and other such matrix group constructors)

**Comment by fingolfin** [comment]
It shouldn't be hard to fix *this particular issue* right now.

However, at this point I am not quite sure how best to deal with this *in general* short of remapping a *ton* of function. Because basically anything you ask GAP about this group will run into this error, because there is no underlying GAP group.

We can improve this a bit by creating a special dummy GAP group as underlying object which is generator-less and has a bunch of properties set (not finite, not finitely generated, not solvable, ...). That would then already take care of a bunch of user queries, e.g. `is_abelian` or `is_finite` etc..

But of course there's always more, e.g. the user might ask for the derived subgroup or derived series or stuff like that -- in each case a GAP error would be triggered. We ultimately need a way to deal with those, too.



But again: this is going way beyond the initial issue about `gens` -- for that we could still apply an immediate (possibly temporary) fix.

**Comment by fingolfin** [comment]
@ThomasBreuer can you have a look at implementing this at least in the special case covered here?

**Comment by ThomasBreuer** [comment]
> can you have a look at implementing this at least in the special case covered here?

I understand this as follows.
The error happens in `assign_from_description`, where `GAP.Globals.GL` is called.
Here we can check whether the given ring is supported by GAP (finite fields, residue class rings, and the ring of rational integers), and throw an exception if not.
(And the same for `SL`, `Sp`, `GO`, `SO`, `GU`, `SU`.)

**Comment by fieker** [comment]
On Wed, Apr 24, 2024 at 03:01:42AM -0700, Thomas Breuer wrote:
> > can you have a look at implementing this at least in the special case covered here?
> 
> I understand this as follows.
> The error happens in `assign_from_description`, where `GAP.Globals.GL` is called.
> Here we can check whether the given ring is supported by GAP (finite fields, residue class rings, and the ring of rational integers), and throw an exception if not.
> (And the same for `SL`, `Sp`, `GO`, `SO`, `GU`, `SU`.)
> 
There are 2 things
 - GL(n, QQ) and friends need to be available as objects
 - for the (many) non-supported functions (for good reason unsupported)
   we need better errors, readable on the Oscar side

**Comment by ThomasBreuer** [comment]
@fieker Yes, the idea is that one can create the object `GL(n, R)`, and that an error message is printed by Oscar just before a GAP function would be called that eventually runs into a GAP error.
