### ISSUE TITLE
Orbits/ Gsets

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#367]
```julia
julia> Oscar.gset_by_type(GH, [1,2], Array{Int, 1})
Oscar.GSetByElements{PermGroup}(Group([ (1,2,3), (1,2), (4,5,6), (4,5) ]), Oscar.on_tuples, [1, 2], Dict{Symbol,Any}())

julia> orbits(ans)
ERROR: Error thrown by GAP: Error, MethodError: no method matching on_tuples(::Int64, ::Oscar.BasicGAPGroupElem{PermGroup})
```

possibly user error (my error)

This is an experiment (failed) to create an transitive representation of an intransitive group by operating on tuples (cartesian product of the "natural" orbits)

**Comment by fieker** [comment]
```
julia> orbit(ans, GH)
ERROR: Error thrown by GAP: Syntax error: String must not include <newline> in stream:1
DeclareAttribute( "JuliaData", IsObject );");
                                          ^^^
Error, MethodError: no method matching on_tuples(::PermGroup, ::Oscar.BasicGAPGroupElem{PermGroup})
```

**Comment by ThomasBreuer** [comment]
I take the first example as a hint about missing documentation and missing argument checks.

The second example also shows a syntax error in the embedded GAP code.
I did not observe it because it does not affect the functionality and because I do not get the GAP error message --why do I not get this GAP error message?
