### ISSUE TITLE
Roadmap OSCAR 1.1

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#3731]
We recently had some discussion about when to make an OSCAR 1.1 release.

The rules are that in this release all book examples must still work, but unlike the 1.0.x releases, some printing relevant for the book may change.

We probably want such a release before the Begehung so that referees see us at our best when they install OSCAR the regular way (i.e. a non-dev release version). Software demos are still free to showcase unreleased features.

The other motivation for having a 1.1 release is so that our tutorials on the website can make use of new features.

However, when we talked about it laste Friday and Wednesday, there was some disagreement on whether we should release this soon, and be willing to have, say another release 1.2 for the Begehung; or whether to delay this as much as possible.

I am opening this issue now (with a week delay, sorry!!!) so we can discuss this further and come to a resolution.

In particular, we should answer this:

1. Do we make a 1.1 release before the Begehung?
   - (if there are things you believe must be dealt with before such a release, feel free to point them out in comments, too) 
3. If yes to 1: Do we make this "soon" (say before the end of May), or do we delay to be really close before the Begehung?
4. If "soon" to 2: OK to make another release (possibly 1.2) just before the Begehung (assuming there is need for it, of course)?

My stance is "yes, soon, yes". I quite frankly did not understand the counter arguments to this made on Friday (e.g. it was claimed that having a 1.1 release would make it appear as if OSCAR was full of bugs and we already need fix releases now. Counterpoint: if this is a concern, then we should quickly get rid of the 1.0.1 and 1.0.2 releases..). Moreover, I'd say this actually looks as if we are very active in adding new features, esp. if we have a proper changelog / news item somewhere that explains this?

But of course I may have misunderstood, so I'll wait for others to explain their concerns

**Comment by micjoswig** [comment]
Indeed, we talked about it last Friday.  For once, we absolutely don't want a rapid sequence of new versions now. Stability is what matters; new features are totally irrelevant for now. 

I think that Janko had a good point when he suggested to produce 1.1 shortly before the Begehung.  This should take of your concerns, without "rocking the boat".

**Comment by afkafkafk13** [comment]
I don't know whether I am allowed to give an opinion here. If not, just ignore my comment.

My view on this is:
There should be a 1.1 release for new features about 10 days before the Begehung, if we can present a nice list of new features (which I expect in view of the developments of the last weeks and the work going on). 
- Not earlier, because this might look like a buggy 1.0 or a try to impress by a rapid-fire of releases. 
- Not later, because it is absolutely natural to release a new minor-version with the new stable features for a special event like the Begehung. The referees are thus given access to these in an official version well in advance of the Begehung.

**Comment by micjoswig** [comment]
👍

**Comment by joschmitt** [comment]
I assume that this can be closed.
