### ISSUE TITLE
Bibliography link anchors inconsistent

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#3760]
Looking at https://docs.oscar-system.org/dev/references/, it seems that for the link of an item the anchor (the thing I can click on) is either the title (maybe for books and things in proceedings?) or the journal information (for articles?).

It looks rather odd.

**Comment by lgoettgens** [comment]
This is not considered a bug by DocumenterCitations.jl but a feature (see e.g. https://github.com/JuliaDocs/DocumenterCitations.jl/issues/63) as this allows for multiple anchors for a single bib entry

**Comment by thofma** [comment]
OK. Is this something we can fix with the style?

PS: I still consider this a bug with how our bibliography looks like. Unless you are saying that we do this on purpose and don't want to change it.

**Comment by fingolfin** [comment]
I don't understand how the linked DocumenterCitations.jl issue justifies this: all the bib items I looked at had a DOI but not an URL field. While that issue is about putting `url` and `doi` links on different text:
> ... should be able to automatically link both a URL and a DOI ...


So I would still suggest we try to appeal this to them. 

But if they refuse this, we should monkey-patch or otherwise hack it, or fork DocumenterCitations. The current behavior is bad.

**Comment by lgoettgens** [comment]
I reported this upstream in https://github.com/JuliaDocs/DocumenterCitations.jl/issues/73 and provided a draft PR for this as well. Let's wait for the DocumenterCitations' maintainer's comments there before we roll something too complicated ourselves.

**Comment by goerz** [comment]
The current behavior is definitely a conscious design decision, see https://github.com/JuliaDocs/DocumenterCitations.jl/issues/73#issuecomment-2355359217. If you only want to have one link (you are careful to only have a DOI or a URL in all entries), then I agree it makes sense to consistently have this link from the title.

I'm open to PRs to `DocumenterCitations` that add [options in the relevant functions](https://github.com/JuliaDocs/DocumenterCitations.jl/pull/74#issuecomment-2355364606) so that it would be easy to change the behavior with a custom style.

**Comment by goerz** [comment]
I just tagged DocumenterCitations 1.3.4 with the fixes from https://github.com/JuliaDocs/DocumenterCitations.jl/pull/74

**Comment by lgoettgens** [comment]
Thanks a lot for getting this in this quickly!!
