### ISSUE TITLE
Make *infinite* polycyclic groups available in GAP

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#432]
Right now the OSCAR type `PcGroup` wraps GAP's `IsPcGroup` -- that's the pc group implementation from the GAP library, which only supports finite ones.

But we really want to also support *infinite* ones. Those are supported by the GAP package `polycyclic` (which GAP loads by default), they are called "pcp groups" (just because they had to have a different type) and teste for with the filter `IsPcpGroup`.

We really should make *those* available. Either in addition or instead of the "built-in" ones. For the regular user, it'd be less confusing if we offered only one, but we need to investigate if this might cause issues in some cases...

(CC @ThomasBreuer)

**Comment by ThomasBreuer** [comment]
Currently we have `_gap_filter` which relates the Julia type of the group to a GAP filter.
Thus it seems to be conceptually not possible to have one Julia type for both `IsPcGroup` and `IsPcpGroup`, depending on the situation.
It would be possible to use `IsPcpGroup` also for finite groups.
(I will make an experiment: Exchange the relevant lines in the Oscar code, and see what happens.)

**Comment by ThomasBreuer** [comment]
O.k., the problem is that GAP creates `IsPcGroup` groups in various situations, where we cannot force `IsPcpGroup` objects. The (few) failing tests happen in situations where such a group occurs as domain or codomain of some mapping inside GAP, and we cannot simply replace it by an `IsPcpGroup` group before the Julia side gets access to the mapping.

Is there a reason why `IsPcGroup` does not imply `IsPcpGroup`, except for historical reasons?
(I make another experiment ...)

**Comment by fingolfin** [comment]
Those two are completely disjoint implementations, and an implication would be wrong and probably  lead to lots of errors.

Unfortunately I believe that some library functions will only work efficiently for IsPcGroup (eg because they use a Pcgs), not for (finite) IsPcpGroups. 

Then again, I might be wrong or too negative (as in: perhaps not that much or even nothing fails and we can easily fix it)... there is always `IsomorphismPcGroup` which is quite efficient for pcp groups...

**Comment by ThomasBreuer** [comment]
O.k., if the filters `IsPcGroup` and `IsPcpGroup` express two different and incompatible internal structures then we can introduce a "common roof" `IsPolycycliclyPresentedGroup` or so that is implied by both and that can serve as `_gap_filter` for the Oscar type `PcGroup`.
The Julia side can then abstractly deal with finite and infinite polycyclic groups, and internally the code can either use a uniform interface (such as `IsomorphismPolycyliclyPresentedGroup`) or distinguish between the two possible implementations in GAP (by calling `IsomorphismPcGroup` or `IsomorphismPcpGroup`).

**Comment by fingolfin** [comment]
@ThomasBreuer what's the status of this, isn't this resolved?

**Comment by ThomasBreuer** [comment]
We can regard this issue as resolved in the sense that Oscar's `cyclic_group(PosInf())`, `dihedral_group(PosInf())`, etc. are based on GAP's `IsPcpGroup`.
