### ISSUE TITLE
Introduce (resp. import from Hecke) `coefficient_ring` for our polynomial rings (including decorated)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#454]
... instead of `base_ring`, and use it consequent in code and examples. (Note that Hecke already defines `coefficient_ring`, we should extend and use it in Oscar).

For a "plain" mpoly (ring), this returns precisely the coefficient ring that was used to construct it. For a decorated mpoly (ring), this returns the `coefficient_ring` of the wrapped mpoly (ring).

If you create a polynomial ring R whose coefficients are another polynomial ring Q which is defined over say F_2, and you want F_2, then you need to write `coefficient_ring(coefficient_ring(R))`

We may want to introduce a similar function for modules, although I am not sure whether `coefficient_ring` is the best name (in GAP we use `LeftActingDomain` -- not saying this is better, just mentioning it for reference).

CC @fieker @wdecker

**Comment by thofma** [comment]
Very much in favor of this.

**Comment by wdecker** [comment]
We disussed this last Wednsday within the "algebraic geometry gang" and agreed that it is important to consequently implement the "one-up" principle. I understand that Max' suggestion is to realize precisely this. We have no problems with using coefficient_ring instead of base_ring. I personally support the change. So yes, go ahead!

**Comment by thofma** [comment]
There is now `coefficient_ring` (which is just an alias for `base_ring`) for all types of polynomial rings.
