### ISSUE TITLE
Use of non-ASCII characters in output

### ISSUE THREAD

**Issue by thofma** [oscar-system/Oscar.jl#569]
This came up in #568 but should be discussed with all stakeholders. In #568 there was the idea to print `ζ_4` instead of `z_4`, which means introducing non-ASCII characters in the output. Do we want to allow this? The question is *only* about printing.

CC'ing some people which already thought about this: @wdecker, @fingolfin, @fieker

**Comment by fieker** [comment]
On Fri, Jul 16, 2021 at 05:22:07AM -0700, Tommy Hofmann wrote:
> This came up in #568 but should be discussed with all stakeholders. In #568 there was the idea to print `ζ_4` instead of `z_4`, which means introducing non-ASCII characters in the output. Do we want to allow this? The question is *only* about printing.
> 
> CC'ing some people which already thought about this: @wdecker, @fingolfin, @fieker 
> 
I guess there is more to it:
 QabField() should also return "gen", ie. a function to compute z(n)
 it should have an (optional) argument to set the printing name of z
   (is this possible? printing a function nicely)
 the printing of QabFieldElem needs to (possibly) also print z(4) rather
   than z_4 (or zeta)
 then finally there is the question about the default being zeta rather
 than z...

**Comment by thofma** [comment]
Yes, I am currently redoing the Q^ab printing as you suggested, but this is kind of unrelated to the issue here. The question about non-ASCII characters needs to be discussed/decided.

**Comment by ThomasBreuer** [comment]
There are several issues about the question of supporting non-ASCII characters in output or not:
#318, Nemocas/Nemo.jl/issues/1013, Nemocas/AbstractAlgebra.jl/issues/773, and surely more.
(I had also once brought up the question because of the non-ASCII line drawing characters used in the code for #445, but currently I do not find the relevant comment.)

I think that using non-ASCII characters in the output makes sense in the examples which we have.
A global switch as suggested in #318 sounds good.
One problem is what we want to show in examples in the documentation. I think the shown examples should consistently use only one of the two output modes (either ASCII only or unicode), and this mode is then chosen for testing the examples.

Something similar is done in GAP and some of its packages: Depending on the terminal capabilities (and perhaps on user preferences which one can set at any time), ASCII only mode or unicode mode is chosen for the GAP session, and ASCII only mode is used for the examples that are shown in the documentation --the effect is that the output in the session may look nicer than the one shown in the manual.

**Comment by fingolfin** [comment]
I am fine with printing the graphical characters (used for "box art") @ThomasBreuer mentions. That's because it is "output only", a user never needs to enter these. (Only caveat: ideally these should only be printed if the terminal really supports them).

It is different for things that users also have to enter. Entering `ζ_4` in an editor for many (most?) people will only be possible via copy & paste. Even if `z_4` is also possible, they may not discover that. Worse, perhaps only the printing shows `ζ_4`, but the user cannot enter it this way (only via `z_4`).

Perhaps we can discuss this later today or tomorrow on gather.town.

**Comment by thofma** [comment]
Has been fixed a while ago in #1047
