### ISSUE TITLE
Fix nanosoldier failures / fix loading of GAP package `ferret`

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#652]
I don't know how to reproduce this locally but it does happen consistently in the julia Nanosoldier reports, for example [here](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2021-09/02/report.md), hidden behind a drop-down **1925 packages failed tests on the previous version too**.
Running the same Oscar-release tests locally with a fresh julia nightly works fine.

```
Examples.galois_group: Error During Test at /home/pkgeval/.julia/packages/Oscar/Bh1Um/test/Examples/galois-test.jl:1
  Got exception outside of a @test
  GAP variable Solve not bound
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:33
    [2] getproperty(#unused#::GAP.GlobalsType, name::Symbol)
      @ GAP ~/.julia/packages/GAP/9XZl9/src/ccalls.jl:394
    [3] starting_group(GC::Oscar.GaloisGrp.GaloisCtx{Hecke.qAdicRootCtx}, K::AnticNumberField; useSubfields::Bool)
      @ Oscar.GaloisGrp ~/.julia/packages/Oscar/Bh1Um/experimental/GaloisGrp/GaloisGrp.jl:1146
    [4] galois_group(K::AnticNumberField, extra::Int64; useSubfields::Bool, pStart::Int64)
      @ Oscar.GaloisGrp ~/.julia/packages/Oscar/Bh1Um/experimental/GaloisGrp/GaloisGrp.jl:1257
    [5] galois_group (repeats 2 times)
      @ ~/.julia/packages/Oscar/Bh1Um/experimental/GaloisGrp/GaloisGrp.jl:1253 [inlined]
    [6] macro expansion
      @ ~/.julia/packages/Oscar/Bh1Um/test/Examples/galois-test.jl:5 [inlined]
```

Full log:  https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-09/02/Oscar.1.8.0-DEV-3aada5982c3.log

The same error also appears for a julia 1.7 beta4 backports report: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/4cddbea_vs_d0c90f3/Oscar.1.7.0-beta4-96d9adf6a02.log

This seems to depend on the nanosoldier environment but I have no idea how exactly.

**Comment by fingolfin** [comment]
`Solve` is from the GAP package ferret that we install and load when initializing Oscar. My guess is that somehow this failed (eg because there is no network connection). But that should normally result in Oscar failing to load...

Anyway I am working on a GAP_ferret.jl package which will hopefully address this for good.

**Comment by fingolfin** [comment]
Still happens, and I see [a similar failure in the GAP.jl test suite](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-10/12/GAP.1.8.0-DEV-d31eef5d6b5.log) run by NanoSoldier. I am pretty the reason is that they block network access (probably a good idea from their POV, so I am not complaining). So on the upside, we don't need to worry about it directly; but on the downside, it'd still be good to have this working, so that NanoSoldier will detect *actual* regressions in the future.

**Comment by fingolfin** [comment]
Actually, no, I take that back: the problem is not network connectivity, the problem is more likely to lack of a C/C++ compiler:
```
...
#I  Downloading archive from URL https://github.com/gap-packages/io/releases/download/v4.7.1/io-4.7.1.tar.gz ...
#I  Saved archive to /tmp/gaptempdirVudECf/io-4.7.1.tar.gz.pkgman
#I  Extracting to /home/pkgeval/.julia/gaproot/v4.12/pkg/io-4.7.1 ...
#I  Running compilation script on /home/pkgeval/.julia/gaproot/v4.12/pkg/io-4.7.1 ...
#I  Possible error detected: see log at /tmp/gaptempdirhbDoli/exec-log.txt
#I  Compilation failed (package may still be usable)
...
```
Outcome is the same. 

@benlorenz BTW for polymake, I noticed the following warning [in this report](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-10/12/Polymake.1.8.0-DEV-d31eef5d6b5.log):
```
polymake:  WARNING: rule _4ti2.circuits : CIRCUITS : VECTORS failed: couldn't run 4ti2: circuits -q /tmp/poly36Taaaa0021.mat
polymake:  WARNING: rule _4ti2.circuits : CIRCUITS : VECTORS ( applied to DUAL ) failed: couldn't run 4ti2: circuits -q /tmp/poly36Taaaa0022.mat
```

**Comment by benlorenz** [comment]
> Actually, no, I take that back: the problem is not network connectivity, the problem is more likely to lack of a C/C++ compiler:

If there was no C++ compiler the Polymake tests would fail too (and quite verbose so, I just tried it to be sure), so this is probably something different in the compilation process.

> @benlorenz BTW for polymake, I noticed the following warning [in this report](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2021-10/12/Polymake.1.8.0-DEV-d31eef5d6b5.log):

Thanks for notifying me, it seems there is still an issue with the current version of the wrappers: I chose to use `source` instead of `.` for readability but unfortunately this is might not be available everywhere (it exists in bash and even csh but not in dash). I will adjust this, and maybe get this test to fail instead of falling back to a different algorithm once that is done.

**Comment by fingolfin** [comment]
[Nanosoldier still fails](https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2022-02/08/report.md). This is worrying because it means we are not covered by regression tests performed by the Julia team. The recent kerfuffle with the improved-precompilation-breaks-OSCAR was only discovered by Tim Holy because there is a package *using* Oscar that is covered by Nanosoldier, so the failure to precompile Oscar was discovered. But that's quite tenuous.

Better if we pass directly...

The [report for Oscar.jl](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-02/08/Oscar.primary.log) now fails with this:
```
...
ParaPlaneCurve |    9      9  2.8s
Test Summary: | Pass  Total  Time
NonPlaneCurve |    8      8  2.0s
Experimental.galois_group: Error During Test at /home/pkgeval/.julia/packages/Oscar/tvDdY/test/Experimental/galois-test.jl:1
  Got exception outside of a @test
  GAP variable ConStabilize not bound
  Stacktrace:
    [1] error(s::String)
      @ Base ./error.jl:35
    [2] getproperty(#unused#::GAP.GlobalsType, name::Symbol)
      @ GAP ~/.julia/packages/GAP/zuq1O/src/globals.jl:40
    [3] (::Oscar.GaloisGrp.var"#199#208")(o::Vector{Tuple{Int64, Int64}})
      @ Oscar.GaloisGrp ./none:0
    [4] iterate
      @ ./generator.jl:47 [inlined]
    [5] collect(itr::Base.Generator{Vector{Any}, Oscar.GaloisGrp.var"#199#208"})
...
```
So this is *still* due to the GAP package `ferret`. But now in a different variant.


So on the one hand that means our detection of whether `ferret` is installed is again broken (I see how and why and will submit a PR). On the other hand, it still is the same root cause: we can't download it on the fly in Nanosoldier. So we still need `GAP_package_ferret.jl` to deal with this, as started in https://github.com/oscar-system/GAP_pkg

**Comment by fingolfin** [comment]
Nanosoldier finally passes now, see https://github.com/JuliaCI/NanosoldierReports/blob/master/pkgeval/by_date/2022-03/02/report.md resp. https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-03/02/Oscar.primary.log
