### ISSUE TITLE
Status of Elliptic Curves package

### ISSUE THREAD

**Issue by kirtsar** [oscar-system/Oscar.jl#75]
I'm interested whether the project https://github.com/defeo/EllipticCurves.jl
would be supported by Oscar.

It seems that some main types, such as generic Weierstrass curves, Montgomery and Edwards curves, and points on these curves are currently implemented.

Is there any difference between this package and EllCrv subpackage of Hecke?

**Comment by wbhart** [comment]
The best thing would be to ask @defeo 

As far as I know, this is a different package to the one in Hecke. 

As Julia is an ecosystem of packages and Oscar.jl is just built on a bunch of Julia packages, there's no reason why you couldn't use it with Oscar. But we're not currently planning on writing conversion routines or the like, unless one of us has an application for it and decides to work on such functions.

**Comment by defeo** [comment]
The goal of that package is to provide tools for elliptic curve cryptography, whereas Hecke is more focused on elliptic curves in general, and over number fields in particular.

However, due to lack of time, we haven't touched the package in a while. With the other authors of the package, we just got funding for more development, so we may restart the efforts soon.

I don't know about Oscar's plans, though. I'm not fully convinced that a package for ECC is necessary in a computer algebra system. This is probably going to stay an independent package based on Nemo.

**Comment by wbhart** [comment]
Yeah that sounds like the right strategy. Of course if it is based on Nemo, it shouldn't be too unusable by people who also want to use Oscar (Nemo is part of Oscar).
