### ISSUE TITLE
release 0.1.1

### ISSUE THREAD

**Issue by kalmarek** [oscar-system/Oscar.jl#76]
Currently there is no way of installing `Oscar` other than from master. It is not registered (probably due to failing tests), hence the description in README needs to be changed.

I tried:
```julia
Pkg.add(PackageSpec(url="https://github.com/oscar-system/Oscar.jl.git", rev="v0.1.0"))

  Updating git-repo `https://github.com/oscar-system/Oscar.jl.git`
ERROR: Compat `Julia` not listed in `deps` or `extras` section.
```
Since this is only fixed in `master` you need to get it via:
```julia
Pkg.add(PackageSpec(url="https://github.com/oscar-system/Oscar.jl.git"))
```
Note: now `Pkg.update()` will git pull `Oscar` each time!. this is not what we want our users to experience, hence the need for `v0.1.1`. Before `v0.1.1` the following need to be resolved though.

----

upon `using Oscar` You get (among the barrage of banners ;)
```
WARNING: could not import Hecke.change_uniformizer into Oscar
WARNING: could not import Hecke.genus_symbol into Oscar
WARNING: could not import Hecke.isdefintie into Oscar
WARNING: could not import Hecke.narrow_class_group into Oscar
```
Probably `Hecke` doesn't export those anymore

----

It is not possible to `test Oscar` locally as it's missing `Test` in its deps:
```julia
(tmp) pkg> test Oscar
   Testing Oscar
    Status `/tmp/jl_sQLuE4/Manifest.toml`
  [c3fe647b] AbstractAlgebra v0.8.0
  [9e28174c] BinDeps v1.0.0
  [b99e7846] BinaryProvider v0.5.8
  [631607c0] CMake v1.1.2
  [1f15a43c] CxxWrap v0.8.2
  [3e1990a7] Hecke v0.7.1
  [682c06a0] JSON v0.20.0
  [2edaba10] Nemo v0.16.1
  [f1435218] Oscar v0.1.0 #master (https://github.com/oscar-system/Oscar.jl.git)
  [d720cf60] Polymake v0.2.2
  [ae029012] Requires v0.5.2
  [30578b45] URIParser v0.4.0
  [2a0f44e3] Base64  [`@stdlib/Base64`]
  [ade2ca70] Dates  [`@stdlib/Dates`]
  [8ba89e20] Distributed  [`@stdlib/Distributed`]
  [b77e0a4c] InteractiveUtils  [`@stdlib/InteractiveUtils`]
  [76f85450] LibGit2  [`@stdlib/LibGit2`]
  [8f399da3] Libdl  [`@stdlib/Libdl`]
  [37e2e46d] LinearAlgebra  [`@stdlib/LinearAlgebra`]
  [56ddb016] Logging  [`@stdlib/Logging`]
  [d6f4376e] Markdown  [`@stdlib/Markdown`]
  [a63ad114] Mmap  [`@stdlib/Mmap`]
  [44cfe95a] Pkg  [`@stdlib/Pkg`]
  [de0858da] Printf  [`@stdlib/Printf`]
  [9abbd945] Profile  [`@stdlib/Profile`]
  [3fa0cd96] REPL  [`@stdlib/REPL`]
  [9a3f8284] Random  [`@stdlib/Random`]
  [ea8e919c] SHA  [`@stdlib/SHA`]
  [9e88b42a] Serialization  [`@stdlib/Serialization`]
  [6462fe0b] Sockets  [`@stdlib/Sockets`]
  [2f01184e] SparseArrays  [`@stdlib/SparseArrays`]
  [8dfed614] Test  [`@stdlib/Test`]
  [cf7118a7] UUIDs  [`@stdlib/UUIDs`]
  [4ec0a83e] Unicode  [`@stdlib/Unicode`]

Welcome to Nemo version 0.16.1

Nemo comes with absolutely no warranty whatsoever


Welcome to 

    _    _           _
   | |  | |         | |
   | |__| | ___  ___| | _____
   |  __  |/ _ \/ __| |/ / _ \
   | |  | |  __/ (__|   <  __/
   |_|  |_|\___|\___|_|\_\___|
    
Version 0.7.1 ... 
 ... which comes with absolutely no warranty whatsoever
(c) 2015-2019 by Claus Fieker, Tommy Hofmann and Carlo Sircana

ERROR: LoadError: ArgumentError: Package Test not found in current path:
- Run `import Pkg; Pkg.add("Test")` to install the Test package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:887
 [2] include at ./boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1105
 [4] include(::Module, ::String) at ./Base.jl:31
 [5] include(::String) at ./client.jl:424
 [6] top-level scope at none:6
in expression starting at /home/kalmar/.julia/packages/Oscar/LcnCP/test/runtests.jl:2
ERROR: Package Oscar errored during testing
```

**Comment by fieker** [comment]
On Sun, Jan 19, 2020 at 06:06:49AM -0800, kalmarek wrote:
> Currently there is no way of installing `Oscar` other than from master. It is not registered (probably due to failing tests), hence the description in README needs to be changed.
> 
> I tried:
> ```julia
> Pkg.add(PackageSpec(url="https://github.com/oscar-system/Oscar.jl.git", rev="v0.1.0"))
> 
>   Updating git-repo `https://github.com/oscar-system/Oscar.jl.git`
> ERROR: Compat `Julia` not listed in `deps` or `extras` section.
Stupid Julia package manager
> ```
> Since this is only fixed in `master` you need to get it via:
> ```julia
> Pkg.add(PackageSpec(url="https://github.com/oscar-system/Oscar.jl.git"))
> ```
> Note: now `Pkg.update()` will git pull `Oscar` each time!. this is not what we want our users to experience, hence the need for `v0.1.1`. Before `v0.1.1` the following need to be resolved though.
Once we have functionalifty, I agree. At this point, pulling "all" of
Oscar is just fine - this way one can actually track progress without
being hindered by the release process
> 
> ----
> 
> upon `using Oscar` You get (among the barrage of banners ;)
We tried to deal with the banners. Julia seems to support only 2 modes:
 - never print
 - always print
given that Nemo (e.g.) is also stand-alone, there is no way that you wil
be able to convince Bill to drop the banner. Julia seems to be incabable
of helping there (unless Bill and I are dumb: the banners are printed in
Nemo before the 1st line of Oscar is executed. The dependencies are
dealt with before anyhting else, hence in Oscar.jl I cannot redirect
stdout/ stderr for this (well I can, but it is too late already). While
julia knows that Nemo is loaded by Oscar, we haven't been able to detect
this within Nemo.)
> ```
> WARNING: could not import Hecke.change_uniformizer into Oscar
> WARNING: could not import Hecke.genus_symbol into Oscar
> WARNING: could not import Hecke.isdefintie into Oscar
> WARNING: could not import Hecke.narrow_class_group into Oscar
> ```
> Probably `Hecke` doesn't export those anymore
> 
This is "fixed" temporarily in Oscar.jl now
It is also fixed in Hecke, but the release process takes time...
> ----
> 
> It is not possible to `test Oscar` locally as it's missing `Test` in its deps:
Stupid Julia stupid package manager again.
Well, then why don't you just add it?

**Comment by wbhart** [comment]
I agree we should do a 0.1.1 release. I am here this week, so we can do that if you want.

I believe @fieker has fixed the import from Hecke. @thofma released a new version of Nemo which should in theory cause the tests to pass (just do ]up if you don't have Nemo dev'd).

If you could prepare a PR with the other minor changes you mentioned, I will merge them and do the release.

As previously mentioned, I wasn't able to test everything in the final release because of the mandatory 3 day waiting period for registering Singular.jl. However, of course everything was passing on my machine (the Hecke issues arose since then, I had Nemo dev'd and I had Test installed, apparently).

The delays were because lots of things that were needed for the Oscar release were months behind schedule (in fact, some still haven't been delivered).

The banners are a real pain. The only way around them is to add yet another package OscarBanner.jl which is the first dependency of Oscar and which inserts something into the environment to tell Nemo and Hecke not to print banners. This is a horrible cludge, but we literally spend hours trying to find another way. In the presence of precompilation, it really isn't possible without relying on internals of Julia.

**Comment by kalmarek** [comment]
https://github.com/oscar-system/Oscar.jl/pull/77

Is there a reason why `import Singular` is commented out?

**Comment by wbhart** [comment]
I commented some of the things out in master because Oscar takes too long to start and I was trying to get some work done. You can comment it back in if you want.

**Comment by fieker** [comment]
On Tue, Jan 21, 2020 at 03:30:48AM -0800, kalmarek wrote:
> https://github.com/oscar-system/Oscar.jl/pull/77
> 
> Is there a reason why `import Singular` is commented out?
It is (or not) working. In Julia 1.3 it cannot (I was told due to the
new CxxWrap not being released yet - only one more bug to fix, and
tomorrow definitely...)

**Comment by wbhart** [comment]
Sure, but we don't test Julia 1.3 and it works fine in other versions of Julia. I'm not sure this is the reason it was done, is it?

**Comment by wbhart** [comment]
Ok, I'm wrong. It was in fact @fieker who added this, not me. The reason it was never there in the first place was because it didn't meet the criteria documented in Oscar.jl. Fair enough. Perhaps we were waiting for Julia-1.3 support after all.

**Comment by wbhart** [comment]
Perhaps we should also add a commented out Gap.jl for the same reason (no BinaryBuilder support).
