### ISSUE TITLE
Matrix group elements should act on "vectors". 

### ISSUE THREAD

**Issue by simonbrandhorst** [oscar-system/Oscar.jl#872]
```
julia> g = ZZ[1 0; 0 1]
[1   0]
[0   1]

julia> G = matrix_group([g])
Matrix group of degree 2 over Integer Ring

julia> h = gens(G)[1]
[1   0]
[0   1]

julia> g*fmpz[1,1]
2-element Vector{fmpz}:
 1
 1

julia> h*fmpz[1,1]
ERROR: MethodError: no method matching *(::MatrixGroupElem{fmpz, fmpz_mat}, ::Vector{fmpz})
```

**Comment by fingolfin** [comment]
Thanks for the report.

We could do that -- and probably should because people will end up doing it -- the name `Vector` is a bit unfortunate in that it goads people into using it for vector space elements.

However, formally, I'd say Oscar matrices and Oscar vectors should be used, not Julia ones. A vector would be an element of a vector space / free module:
```julia
julia> g = QQ[1 0; 0 1]
[1   0]
[0   1]

julia> G = matrix_group([g])
Matrix group of degree 2 over Rational Field

julia> h = gen(G, 1)
[1   0]
[0   1]

julia> V = FreeModule(QQ,2)
Vector space of dimension 2 over Rational Field

julia> h * V([1,1])
[1]
[1]

julia> g * V([1,1])
[1]
[1]
```

Alas, note that the example above uses `QQ` not `ZZ`; using `ZZ` currently produces a `method not found` error for the multiplication, because for some reason that code restricts to `FieldElem`. That should be fixed. In general, quite some of the `MatrixGroup` code in Oscar right now restricts itself to working over fields (in many cases for no strong reason other then when it was written, its author only had fields in mind). In any case, I think we should fix that to allow using `Z` or `ZZ/4ZZ` and other such rings.

Further note (to self / anyone working on this issue): the methods for implementing this multiplication are all in Oscar, even though some of them purely concern types defined elsewhere (AA/Nemo/Hecke), which constitutes type piracy, see also PR #760. Those methods should perhaps be generalized and some of them moved to the relevant packages.

**Comment by thofma** [comment]
I am in favour of allowing `Vector` to be acted upon from the left and right. Not having it just inconveniences the user.

**Comment by fingolfin** [comment]
We should indeed do this. See also PR #760 which removes some related code, because the way it is written constitutes type piracy. But that code really is more about teaching existing matrix types to act on various kinds of vectors. This issue is about teaching matrix group elements to act on various kinds of vectors.

For `Vector{T}` instances, we can indeed act from the left and right, if we are willing to dynamically treat them as column or row vectors, depending on which size they are in.

For `fmpz_mat`, and other matrix types, we don't really have freedom in choosing whether to treat them as row or column, and I'd prefer to not add hacks to allow that; the user should rather be explicit and call `tranpose`, I'd say; simply to  help catch errors. What do other think?

**Comment by thofma** [comment]
Acting from left and right on `Vector` is already implemented :) (at least for the matrices, don't know about the matrix group elements.)

And I agree for matrices. Although they might have only one row or column, they are still matrices and we should only allow compatible matrix dimensions in the multiplication.

**Comment by fingolfin** [comment]
To be clear: of course it would be nicest if a `MatrixGroupElem{fmpz}` and an `fmpz_mat` had similar capabilities, and *both* allow to multiply with e.g. a `Vector{fmpz}`. So we could try to add this as a capability to Nemo. But I am not sure if this is acceptable to everyone? If yes, fine, @ThomasBreuer can submit a PR. If not, though, we can of course still support it for `MatrixGroupElem`. 

The same goes for other combininations of arguments, e.g. there is also `AbstractAlgebra.Generic.FreeModuleElem` (see PR #760)...

**Comment by fingolfin** [comment]
@thofma ah excellent (I didn't check what was there before i wrote my comments). We'll make sure to get MatrixGroupElem to support this, too.

**Comment by fieker** [comment]
On Tue, Feb 01, 2022 at 04:53:06AM -0800, Max Horn wrote:
> To be clear: of course it would be nice if a `MatrixGroupElem{fmpz}` and an `fmpz_mat` had similar capabilities, and *both* allow to multiply with e.g. a `Vector{fmpz}`. So we could try to add this as a capability to Nemo. But I am not sure if this is acceptable to everyone? If yes, fine, @ThomasBreuer can submit a PR. If not, though, we can of course still support it for `MatrixGroupElem`. 
> 
> The same goes for other combininations of arguments, e.g. there is also `AbstractAlgebra.Generic.FreeModuleElem` (see PR #760)...
> 
Is this always well defined? Ie. vec * vec could be
 - using "dot", return a 1x1 matrix
 - or an n x n ?
Is it automatically well defined by the dimenstion of the matrix?

**Comment by thofma** [comment]
`Vector * Vector` is not defined and I don't think anyone suggested implementing it.

Then only things we have are the innocent `OscarMatrix * Vector` and `Vector * OscarMatrix` definition.

**Comment by ThomasBreuer** [comment]
When working on pull request #1368, I noticed that there is in fact a method for
`Base.:*(v::AbstractAlgebra.Generic.FreeModuleElem{T},u::AbstractAlgebra.Generic.FreeModuleElem{T})`
in `src/Groups/matrices/matrix_manipulation.jl`.
The above discussion suggests that we should remove it.

**Comment by ThomasBreuer** [comment]
The initial examples are working now, and also the related comments do not have open ends.
