### ISSUE TITLE
What should output look like? (i.e. Base.show)

### ISSUE THREAD

**Issue by lkastner** [oscar-system/Oscar.jl#993]
For polyhedral objects we right now have output like:
```
julia> p = cube(3)
A polyhedron in ambient dimension 3
```
Someone decided we need the ambient dimension in there. (Not all polyhedra have an ambient dimension though) Nevertheless this output conveys the same information for almost all polyhedra. It is similar for the other polyhedral objects as well.

Now the show method of toric varieties has grown to almost 100 lines. The output looks like
```
julia> p2 = toric_projective_space(2)
A normal, non-affine, smooth, projective, gorenstein, q-gorenstein, fano, 2-dimensional toric variety without torusfactor
```
That means it asks for a bunch of cached properties and if these are known it adds them to the output. I am against this, but I want to discuss this, which is why I open this as a question. Here are my reasons:
1. The show method becomes bulky and hard to maintain. (Maybe not super hard, since it just the same pattern all the time)
2. The output is not predictable anymore, which makes testing harder. Everytime we reorder something this output may change as well. (Of course we can suppress it with `;`)
3. The user probably knows these things already, since they are only computed on demand.
4. The output is technically useless as the user cannot access it directly, i.e. they would still need to look at the docs to find the appropriate `is_*` or `has_*` method.

So what do other people think? Probably this is another thing to add to the style guide.

**Comment by fingolfin** [comment]
(I took the liberty of editing your post to number your reasons, to make it easier to reference them; I hope you don't mind.)

First off, I have no strong feeling either way! Some thoughts regarding your reasons:

1. I agree they are bulky, and I find this somewhat annoying. That said, I don't think maintaining them is a serious problem; but this point certainly make me less interested in implementing similar methods for e.g. groups (although in a sense in issue #987 we discuss doing something similar for `describe(::GAPGroup)`, so I might have to do it anyway :joy:)
2. This can be an issue if variables are used across multiple tests (this hits us in GAP regularly), but I don't think we even do this (or even *can* do this?!?) in our doctests, so I am not sure how this is worse than any other change to printing? `using Oscar ; Oscar.build_doc(; doctest=:fix)` should take of it, anyway (as long as one remember to use Julia 1.6 for this)
3. Not so sure; at least in GAP, often asking for one thing computes others. E.g. if I ask whether an fp group is finite, then usually that actually computes the size, and from that it may deduce that the group is solvable. That said, one can indeed wonder how useful it is for the user to get this long list of known properties. If they truly want to know if the toric variety is smooth they can call `issmooth`; ideally we'll also offer a uniform way to test if a property is known (e.g. `has_issmooth(tv)` or `knows(issmooth, tv)` or so; I'd rather avoid `has_attribute(tv, :issmoth)` as that relies on an implementation detail; anyway this is something we should discuss elsewhere)
4. I don't quite understand your point here (sorry!). Here's my naive thought: Of course this output is only of interest (if at all!) for use in the REPL. So if I see the toric variety is smooth, I am happy and I can go on; I don't need to call `issmooth(tv)` to confirm this. Perhaps you can elaborate?

All in all, I'd say I don't find this output very useful, but I also don't see it as very problematic. But I do agree that it'd be nice to handle this somewhat consistently (i.e. ideally "all" types print a lot, or none; though in practice we should of course be pragmatic and allow variations if domain experts find it super useful). And then perhaps we should think economically, which means not too print too much, so that we don't have to write complex functions printing lots of data for lots of types. 

Anyway, I would find it interesting to here what @HereAround thinks, and what his motivation for the printing of toric varieties was/is.

**Comment by lkastner** [comment]
Oh, 4. just means that any methods using any of the properties should have the appropriate check. But I agree, I guess I was only a little surprised by the length of it. It would be nice to solve this consistently though. And maybe for toric varieties it can be refactored into something shorter.

**Comment by HereAround** [comment]
Here is what my rational was:
- I was unsatisfied with the original display message. For my taste, it provided too little information. (In particular, I do not care too much about the ambient dimension of the fan. The dimension of the variety would seem more natural to me.)
- I had logical implications in mind (a different and subtle matter - I know). So I anticipated that the user (or I) would not necessarily have explicitly triggered computations for all currently known properties/attributes (same as @fingolfin says above in point 3).
- Convenience: Once the attributes were cached, it was easy enough to make use of them to print-out all known properties.

Still, I think you both have valid points. First, maintenance and tests are a good point. The doc-tests need to be updated as we change the display method. Also, a consistent solution across other areas (rings, groups, etc.) would be good.

A proposal towards this:
- Reduce the display method to some basic information (e.g. "A 3-dim. toric variety").
- Add a  `display_all` or `full_information` method that prints it all.

What do you think?

**Comment by lkastner** [comment]
For now I will just condense the code a little.

**Comment by lkastner** [comment]
Also I think the logic is messed up in this particular case. Take e.g.
```
   # smooth/simplicial?
    if has_attribute(v, :issmooth)
        if get_attribute(v, :issmooth)
            push!(properties_string, "smooth")
        else
            if has_attribute(v, :issimplicial)
                if get_attribute(v, :issimplicial)
                    push!(properties_string, "simplicial")
                else
                    push!(properties_string, "non-smooth")
                end
            end
        end
    end
```
If `:issmooth` isn't set, it will not drop into the `:issimplicial` block, even though this could be known. Furthermore, `:issmooth` could be false, but `:issimplicial` is not set for one reason or another. Then it will not print `non-smooth`.

Also isn't non-simplicial stronger than non-smooth?

Similar problems in the `complete/projective` section: I for some reason `iscomplete` is not set, it never checks the `isprojective`. If the thing has `iscomplete=true` and `isprojective=false` it does not print anything, even though it could print `complete + non-projective`.

I will now just untangle all of these and then the user might get redundant information, but this is better than before.

**Comment by fingolfin** [comment]
I don't know what the implications between "smooth" and "simplicial" are, but my guess regarding the intention of the code would be that it is meant to hide "obvious" implications; e.g. to a group theorist, printing "an abelian, solvable group" would look silly, as abelian implies solvable, so you'd only want to print "an abelian group" in that case. Whereas it makes sense to print "a non-abelian, solvable group" and also "a solvable group" (if nothing is known about the commutativity of the group).

**Comment by lkastner** [comment]
Sure, that's also how I understood it. However there were a few holes. I hope I didn't make any new ones though.

**Comment by HereAround** [comment]
Indeed, I was trying to suppress/hide obvious implications. Still, I think @lkastner has a point. Even if `:issmooth` is not set, it is possible that it is known if the variety is issimplicial. Still, no information about this is printed by my code. Similar for `complete/projective`.

Regarding the other points raised, opinions towards a simplistic `base.show` method and a more involved `display_all` or `full_information` method?

The advantage would be that we can display a basic print-out from `base.show` (such as "a 3-dim. toric variety" or alike) in the doc-strings/the documentation. Even if the `display_all` or `full_information` method is adjusted (e.g. to reflect a new attribute/property being supported), no change to the doc-tests are needed. So this would be more efficient towards future developments.

**Comment by thofma** [comment]
How about extending `describe` for this? Just thinking out loud here. So far it is restricted to groups, where we try to give a more helpful display of a group (e.g. `C_2` instead of `pc group blabla`). It also no guarantees etc.
